### ISSUE TITLE
docs on the data model

### ISSUE THREAD

**Issue by dcsan** [reactGo/reactGo#112]
I'm new to redux, so I'll go and readup on that.. but it would be great to have a few steps on how to add another model. 

Some of this code seems to be a few layers abstracted, making it quite opaque to grok for the newbies like me who are looking for this type of starter kit...
eg:

```
    this.onEntrySave = this.onEntrySave.bind(this);
...
  onEntrySave(text) {
    const { dispatch } = this.props;
    dispatch(createTopic(text));
  }
```

so you are creating abstract components and passing in the save/handler methods?

If i wanted to just create a new component without that indirection is that still required boilerplate for using Redux?

```

export default class Editor extends React.Component {

  onEntryChange(text) {
    const { dispatch } = this.props;
    dispatch(typing(text));
  }

  onEntrySave(text) {
    const { dispatch } = this.props;
    dispatch(createTopic(text));
  }

  render() {
    return (
      <div className='editor-box' >
        <h1>This is the editor</h1>

        <EntryBox topic={this.props.newTopic}
          onEntryChange={this.onEntryChange}
          onEntrySave={this.onEntrySave} />

      </div>
    );
  }
};
```

gives

> Uncaught TypeError: Cannot read property 'props' of undefined

so I'm trying to understand in your other components where props.dispatch is imported from.

**Comment by dcsan** [comment]
probably something to do with this... ?

```
function mapStateToProps(state) {
  return {
    topics: state.topic.topics,
    newTopic: state.topic.newTopic
  };
}

// Read more about where to place `connect` here:
// https://github.com/rackt/react-redux/issues/75#issuecomment-135436563
export default connect(mapStateToProps)(Vote);
```

**Comment by choonkending** [comment]
@dcsan Thanks very much for raising this! I'll add more docs for sure. 

Q1
> so I'm trying to understand in your other components where props.dispatch is imported from.

I use redux with `react-redux` which provides a [connect](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) function to use with React components.
 
>  Any component wrapped with connect() call will receive a dispatch function as a prop, and any state it needs from the global state. In most cases you will only pass the first argument to connect(), which is a function we call a selector. This function takes the global Redux store’s state, and returns the props you need for the component. In the simplest case, you can just return the state given to you (i.e. pass identity function), but you may also wish to transform it first.

Q2
> If i wanted to just create a new component without that indirection is that still required boilerplate for using Redux?

Nope. If you're using `react-redux`'s `connect` method, you can use `dispatch` on any level on component without that indirection. However, be aware that it might make data flow harder to trace. 

> Try to only do this for a top-level component, or route handlers. While technically you can connect() any component in your app to Redux store, avoid doing this too deeply, because it will make the data flow harder to trace.

Excerpts from redux [docs](http://rackt.org/redux/docs/basics/UsageWithReact.html)

Let me know if that helps!

**Comment by psimyn** [comment]
@dcsan, `connect` is what will add the dispatch method to your props. But the error you are getting is due to `this` being undefined in your handlers.

Can either do this:

```
<EntryBox topic={this.props.newTopic}
          onEntryChange={this.onEntryChange.bind(this)}
          onEntrySave={this.onEntrySave.bind(this)} />
```

or this:

```
export default class Editor extends React.Component {
    contructor(props) {
        super(props);
        this.onEntryChange = this.onEntryChange.bind(this);
        this.onEntrySave = this.onEntrySave.bind(this);
    }

    ...
```

**Comment by choonkending** [comment]
Scratch option one. 

@psimyn As you mentioned to me today, 

> " bind(this) should happen once in the constructor and not on every render. Otherwise it causes an always true component update
