### ISSUE TITLE
Add helmetJS

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#119]
https://github.com/helmetjs/helmet

Better security. 
Also follow the steps here. We want good practices here.

https://strongloop.com/strongblog/best-practices-for-express-in-production-part-one-security/

**Comment by psimyn** [comment]
I think all done @choonkending ?

**Comment by choonkending** [comment]
not sure if I did it :(

**Comment by choonkending** [comment]
Yep, have not done this yet. This is the helmet for security.
