### ISSUE TITLE
Redux saga?

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#124]
https://github.com/yelouafi/redux-saga

Redux-saga looks like a nice way of handling side effects. So far I do not think I've met any big challenges with using redux-thunk. But if it is a worthy candidate, and if anyone has any thoughts, please let me know.

**Comment by joshhornby** [comment]
I really like the look of https://github.com/redux-effects/redux-effects

Seems a little cleaner than redux-saga.
