### ISSUE TITLE
export constants from actions?

### ISSUE THREAD

**Issue by charlieclark** [reactGo/reactGo#136]
More a suggestion than an issue -
It feels a bit more organized and DRY to export the actions constants from the action itself.
eg: https://github.com/caljrimmer/isomorphic-redux-app/blob/master/src/common/actions/reddit.js

**Comment by choonkending** [comment]
@charlieclark I have been thinking about this myself. I think it's an excellent idea, because then the when we import it in reducers as well, it would actually give the user more context as to where the action came from.

**Comment by slavab89** [comment]
This is a pretty old issue and we're currently in a process of cleaning up the project's issues. Quite a lot of things have changed since this issue was raised. If you still think this is relevant, feel free to comment here or open a new issue.
