### ISSUE TITLE
Better unit tests

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#140]
This has been a particularly pain point for me.

`nock` has been working pretty well since we started with unit tests, however since introducing to `axios` to `actions/topics` (and eventually replacing isomorphic-fetch across the app with axios), I had to comment out the particular test in https://github.com/choonkending/react-webpack-node/commit/be1bb3ebdd29e457d0cd89dec98ce29397e4566f

Will be looking into this, but also appreciate any help/opinions about better unit testing.

We would like to increase overall test coverage to ^ quality of the code delivered with this boilerplate.

**Comment by yanivefraim** [comment]
@choonkending is this still relevant? What about support for server side tests (using mocha/node), and e2e tests (Nightwatch/protractor)?

**Comment by choonkending** [comment]
@yanivefraim Sorry for the late reply. Yes, this issue isn't exactly 100% relevant now. 

I think server-side tests should be added in, but for now e2e might not prioritised. We're looking at cleaning up the code in this boilerplate for now :)
