### ISSUE TITLE
CSS modules with classnames is painful

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#147]
Was working on a hackday project with this today. With the const cx('B__e--m') it gets painful pretty fast.

**Comment by caranicas** [comment]
Hi love this project. it was everything I needed to get started, and been a tremendous learning tool (once I did all the redux videos on egghead). But yeah this class module loader is really painful. It was making it difficult to get some sass in a node module to match my selectors. My sass was compiling with the hash but the component that was being injected had the pure selectors. After I spent an hour trying to make it work I investigated the source of the hash. 

I  removed  `__[hash:base64:5]` from the loader `style!css?module&localIdentName=[local]` in the dev config. and that solved my issue. 

I read about the hash in webpack's css loader and while i understand it to a degree, it seems to make things more complicated than it's worth. I'd love to learn more, why do you consider this a better practice? Or are you also starting to reconsider this?

**Comment by choonkending** [comment]
@caranicas Hey, thanks for joining in the fun :smiley: 

Apologies for the late reply, because I really needed to read up on all this.  

> why do you consider this a better practice? 

- Truly modular and reusable CSS
- No more naming collisions (Although if you are dealing with legacy codebase with bad CSS, there will still be overriding issues). 
- Composability

```css
.foo {
  composes: heading from './typography.css';
  composes: box from 'layout.css';
}
```

You could map many classes to a single class for your component. I personally have not tried composing yet, but after reading up on this, I'm pretty pumped to come up with better CSS.

> Or are you also starting to reconsider this?

I think my usage of BEM in this repo might be redundant with using CSS modules. Because the idea of BEM is to locally scope components as blocks, so that styles do not leak to other components. 

What was causing me pain was not actually the usage of CSS modules, but the unnecessary naming because I still wanted to stick to BEM styling. In the case of CSS modules, I believe camelCasing the component simply will suffice.

So my answer is that I think we *should* stick with CSS modules as it is the future. We might even move to [jss-loader](https://github.com/markdalgleish/jss-loader) if we find the need for that.

Also will have to refactor all the css files.

Might be worth just doing the below in most cases, without relying on `classnames`.

```javascript
import styles from 'bla.scss';

...
return (
<div className={styles.header}></div>
);

```

Interested to know your thoughts as well @psimyn. Happy to be corrected. 

### Good references
- Watch [The case for CSS Modules](https://www.youtube.com/watch?v=zR1lOuyQEt8)
- Read [CSS Modules](https://github.com/css-modules/css-modules)

**Comment by caranicas** [comment]
Thanks for the resources I will def check them out. 

I actually did resort to ` <div className={styles.header}></div>` in my naming, but my issue wasn't with classNames, per say,  but the `__[hash:base64:5]` that was getting affixed to many of my class names. Can you maybe speak to why you felt it was necessary to include that?

**Comment by psimyn** [comment]
@caranicas the hash is just a way to ensure class names are unique, without being too long. You can set it to moduleName-className or similar if you prefer, using a hash just means there's a _very_ good chance nothing else will conflict with your styles (e.g. other classes, third party CSS, etc)

@choonkending jss looks good, I think that loader has been on hold due to  https://github.com/markdalgleish/jss-loader/issues/2

I am currently waiting out this https://github.com/babel/babel/pull/3376

**Comment by markopavlovic** [comment]
@psimyn @choonkending 

My problem is when you want your styles to conflict with other components and libs where you maybe don't have a complete control over the css and where you are trying to customize the element by adding a custom css class.

For example:
```
<div class="boostrapClassX hashed__7171__customClass">
 <div class="boostrapChildClassX"></div>
</div>
```

In which case the following css won't work:
`.customClass .boostrapChildClassX { display:none }`

as `.boostrapChildClassX` will not get hashed while the element in DOM will stay `boostrapChildClassX` if its an element rendered by node_modules lib that doesn't go through its webpack loader.

So the solutions are following:
1. Pull the lib through webpack loader. (ugh)
2. Remove hashing and use a simple style guide for class naming which solved this problem long ago and created consistency within css code.
3. ?

**Comment by caranicas** [comment]
@markopavlovic this was exactly the issue I ran into. I went with option 2. Seemed like the best way to move forward quickly. My project wasn't too big and I trust myself to write well scoped css.

Option 3 is whatever the best practice is. Sadly I don't think that has been figured out yet. CSSNext  is still pretty new, and the pain points are still being worked out.

**Comment by psimyn** [comment]
@markopavlovic unless I'm misunderstanding, you can use combination of global classes with generated ones. 

```
.customClass :global(.boostrapChildClassX)  { display:none }
```
