### ISSUE TITLE
use CommonsChunkPlugin make error

### ISSUE THREAD

**Issue by HellMagic** [reactGo/reactGo#192]
Hi, guys, when i use CommonChunkPlugin in webpack.prod.config follow the guide from the webpack, but i got some error, and the error is different if i place the plugin in different env, like browser and serverside. i think i should config both them, but when i place the plugin in **serverside**, then i start server, send the request, and i got **App.default is not a function** error message. i think i understand well the awesome project boilerplate, i have tried as possible as i can but still cannot fix it...and, i tried to place the common plugin in the browser config, there is no error in server like above, but i got an error  **webpackjsonp is not defined** in my **client browser**, i google and most answer means maybe not include the common js file, but i double check the file is right there, so i check the webpack doc but not help.

this is my webpack.prod.config.js file like(just add the commonChunkPlugin support)：

**(i apologize for my code format, i tried to make more pretty ...hope it also clear)**
`
    module.exports = [
        {
            name: "browser",
            devtool: "source-map",
            context: path.join(__dirname, "..", "app"),
            entry: {
                app: "./main/client",
               //Note: Here add the vendroConfig Array variable, like : ["react", "react-dom"] and so on
                vendor: vendorConfig  
        },
        output: {
            path: assetsPath,
            filename: "[name].js",
            publicPath: publicPath
        },

```
    module: {
        loaders: commonLoaders
    },
    resolve: {
        extensions: [''", ".js", ".jsx", ".css"],
        modulesDirectories: [
            "app", "node_modules"
        ]
    },
    plugins: [
       // **"Here add CommonChunkPlugin in "browser" module.exports, and this make client error**
             // **webpackjson is not defined"**
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
        new ExtractTextPlugin("styles/main.css"),
        new webpack.optimize.UglifyJsPlugin({
            compressor: {
                warnings: false
            }
        }),
        new webpack.DefinePlugin({
            __DEVCLIENT__: false,
            __DEVSERVER__: false
        }),
        new InlineEnviromentVariablesPlugin({ NODE_ENV: "production" })
    ],
    postcss: postCSSConfig
}, {
    name: "server-side rendering",
    context: path.join(__dirname, "..", "app"),
    entry: {
        server: "./main/server"
    },
    target: "node",
    output: {
        path: assetsPath,
        filename: "server.js",
        publicPath: publicPath,
        libraryTarget: "commonjs2"
    },
    module: {
        loaders: commonLoaders
    },
    resolve: {
        extensions: ["", ".js", ".jsx", ".css"],
        modulesDirectories: [
            "app", "node_modules"
        ]
    },
    plugins: [
       //**Here if i add CommonChunkPlugin in "serverside" module.exports, and this make error**
             // **"App.default is not a function"**
        // new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
        new webpack.optimize.OccurenceOrderPlugin(),
        new ExtractTextPlugin("styles/main.css"),
        new webpack.optimize.UglifyJsPlugin({
            compressor: {
                warnings: false
            }
        }),
        new webpack.DefinePlugin({
            __DEVCLIENT__: false,
            __DEVSERVER__: false
        }),
        new InlineEnviromentVariablesPlugin({ NODE_ENV: 'production' })
    ],
    postcss: postCSSConfig
}
```

];
`
i really cannot fix where is wrong, so please help me let know, any help or suggest is appreciate, thanks very much !!! Looking forward your reply ~~~

**Comment by psimyn** [comment]
Few things, I'll put dot points and can explain if anything is unclear:

 - you don't need common chunk plugin for server config
 - since you are specifying dependencies in the vendor entry point, the commonchunk won't actually do anything
 - are you including both the vendor and app entry points in your HTML?

**Comment by HellMagic** [comment]
@pslmyn thanks for your reply!!!
- you mean i just need to config common chunk plugin for browser config?
- i don't understand this, you mean i write wrong something?
- yes, i including both the vendor and app entry points in the html string of server.jsx file

that's all, anything i miss?

**Comment by psimyn** [comment]
> you mean i just need to config common chunk plugin for browser config?
yep, you can have it in server config, but I don't think it will be used

> i don't understand this, you mean i write wrong something?
CommonsChunkPlugin works by checking what modules are used in a lot of places, and _automatically_
takes them into the common chunk. Since you are manually specifying vendor modules in your `vendor` entry point, there will probably be no benefit to using it (unless you have some vendor libraries that _aren't_ common)

Common chunk is generally used on your main module, e.g.

```
new CommonsChunkPlugin({
    name: 'app',
    minChunks: 3
  })
```

This will move any JS modules included in more than 3 places into a common chunk, and that will be automatically loaded by including "app" in the page.

Hope that makes some sense

**Comment by slavab89** [comment]
This is a pretty old issue and we're doing a issue cleanup on the project.
Please check the codesplit and ssr PR's if you still have an issue with this. Feel free to comment here or open a new issue if you still need help.
