### ISSUE TITLE
Fix Hot Module Reloading

### ISSUE THREAD

**Issue by mjewell** [reactGo/reactGo#195]
As far as I can tell, hot module reloading doesn't actually work. The page fully refreshes whenever you change any app code. Also, it looks like https://github.com/gaearon/react-transform-hmr is deprecated, so we should swap that out.

**Comment by choonkending** [comment]
Thanks. I didn't know hmr got deprecated, we should definitely swap it out.

The way it's set up, hot reloading only works on client side code unfortunately :( I'll have a look as part of using hot reloader 3

**Comment by mjewell** [comment]
As far as I know it is only a client side thing, right? But the client side should be able to reload without a full page refresh if you're only changing client code and I don't think that's the case right now. For me at least, the page refreshes, albeit automatically

**Comment by choonkending** [comment]
Weird. Must have regressed recently. It shouldn't need to refresh.

Only the folders covered in `nodemon` triggers a full page refresh.

**Comment by choonkending** [comment]
@mjewell Hey, I tried `npm run dev` and editing `Vote.jsx` appears to work with hot reloading.

<img width="748" alt="screen shot 2016-04-19 at 6 23 53 pm" src="https://cloud.githubusercontent.com/assets/3787885/14632464/27d05306-065c-11e6-9d48-903357806ba0.png">

The files that are not watched by the transform-hmr are:
     - "app/server.jsx",
     - "app/routes.jsx",
     - "app/helmconfig.js",
     - "app/components/Meta.jsx",
     - "server",
     - "webpack"

The reason why we need nodemon is because of the following line in webpack-dev-client.js
```javascript
// THe only files watched by the middleware are from `client.js` entrypoint
    entry: {
      app: ['./client', hotMiddlewareScript]
    },
```
Can you tell me which file you tried editing?

That aside, we will definitely move towards react hot loader 3 now :)

**Comment by AJIh** [comment]
@choonkending Hi, I tried editing different files. In most cases(whether .jsx or .css), HMR works greatly. However,  a full page refresh is triggered when editing `app/css/common/colors.css`.

I tried to update react suites to 15.0.1 by myself, which I am not sure is the reason causing the refresh.

**Comment by AJIh** [comment]
postcss/postcss-simple-vars#37 Maybe the issue is saying the same thing. :)

**Comment by mjewell** [comment]
Hmm, strange. It works for me if I edit components too. I was editing a reducer, trying to replicate what they show in the gif at the top of [the redux devtools repo](https://github.com/gaearon/redux-devtools), and that seems to show an error in the console and then a full page refresh for me, but it loads too quickly for me to see what the error is.

**Comment by MrSkinny** [comment]
Hi there. Coming in completely fresh, I did:

```
npm install
npm run build
heroku create
git push heroku master
```

and the production site fails to load with console error:
`index.js:51 Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr`

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it. Moreover, the code has changed quite a lot since this issue was opened.
If you still experience this or have an issue, please comment here or open a new one
