### ISSUE TITLE
Separate npm dependencies

### ISSUE THREAD

**Issue by ccorcos** [reactGo/reactGo#197]
Is it possible to separate the npm dependencies? How would you hande a react native app here?

**Comment by choonkending** [comment]
Thanks for raising an issue.

Do you mean separating npm dependencies to prod and dev dependencies?

I haven't used react native in a while, or in this project, so I'm not sure
what the complexity involved will be.

Can you elaborate on your question?

**Comment by ccorcos** [comment]
I mean separating the npm dependencies, as well as versioning, between node, react-web, react-native, and whatever else might be going on. That way everything is more decoupled.

**Comment by psimyn** [comment]
I think react-native would be a separate repo - "separating dependencies and versions" implies different `package.json`s

and for this the web/node bits are inherently coupled

**Comment by ccorcos** [comment]
With a separate repo, how do you share code then?

**Comment by psimyn** [comment]
`npm install` ?

**Comment by ccorcos** [comment]
so you have to version all the shared code with separate npm pacakges?

**Comment by psimyn** [comment]
isn't that what you meant by separating "versioning, between node, react-web, react-native, and whatever else might be going on"?

I don't think I fully understand what you're trying to do. If keeping with this repo you could presumably just `npm install react-native` in the root directory, then add your project.

Potentially some info/examples on their docs https://facebook.github.io/react-native/docs/embedded-app-ios.html and this thread: https://github.com/facebook/react-native/issues/4717

**Comment by ccorcos** [comment]
Well the thing is, your server package.json and your frontend package.json share all the same dependencies...

**Comment by caranicas** [comment]
@ccorcos I think I understand what you are saying but I think you are misunderstanding the point of this repo. React native is not part of this boilerplates mission. 

While we have enabled a certain degree of configuration. It is all centered around the server environment. Building a boilerplate that would be robust enough to contain best practices across all environments and a way to configure your build target would be Herculean effort.

I am sure there are people in some corner of the internet working on that, but we are not. if that is something you are interested i would wholeheartedly suggest you attempt it. 

if you are just looking for a react native boilerplate i a bunch with a quick google, but these two looked the best.

https://github.com/LeoLeBras/react-native-redux-starter-kit
https://github.com/bartonhammond/snowflake


I hope this helped.
