### ISSUE TITLE
sequelize db:migrate not working on Heroku

### ISSUE THREAD

**Issue by coderjonny** [reactGo/reactGo#218]
Hi, 

I did all the following steps for creating a PG db on Heroku, but when I try to do a migration it doesn't work and I get this error:

```
heroku run sequelize db:migrate
Running sequelize db:migrate on murmuring-refuge-53970... up, run.1235

Sequelize [Node: 5.11.0, CLI: 2.4.0, ORM: 3.22.0]

Loaded configuration file "server/db/sequelize/sequelize_config.js".
Using environment "production".
Unable to connect to database: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
```

Any ideas?

**Comment by mjewell** [comment]
You need to define an environment variable called POSTGRES_DB_URL which points to your postgres database. As far as I know if you follow the steps in `docs/databases.md` for installing on heroku this will be done for you. If not, you can always manually add the env variable in heroku yourself as long as you know the db url.

If you look at `/server/db/postgres/sequelize_config.js` you will see that it has this object in the production environment:

```
production: {
  use_env_variable: 'POSTGRES_DB_URL',
  username: process.env.PGUSER || 'root',
  password: null,
  database: 'react_webpack_node_production',
  host: '127.0.0.1',
  dialect: 'postgres'
}
```

Sequelize will preferentially choose the use_env_variable route, but if it can't find it it will resort to using the other settings. In your case it appears as though this is what is happening.

**Comment by coderjonny** [comment]
Hi Michael, 

Thanks for the reply. I have that ENV var setup on heroku: 
```
heroku config
=== murmuring-refuge-53970 Config Vars
DATABASE_URL:    postgres://xqanrsonubojqi:QOYq60l3JOcaf9WhE8qCcoBsds@ec2-23-21-66-88.compute-1.amazonaws.com:5432/dff94od760b4n8
POSTGRES_DB_URL: postgres://xqanrsonubojqi:QOYq60l3JOcaf9WhE8qCcoBsds@ec2-23-21-66-88.compute-1.amazonaws.com:5432/dff94od760b4n8
```

When I do heroku logs.. it looks like it ``` Successfully connected to sequelize database ```
but when I try to do a migration, it can't connect.

**Comment by mjewell** [comment]
Hmm, I will have to look into that a little later, nothing obvious springs
to mind.

BTW, that URL string contains your username and password for the postgres
db, so you will want to update that

**Comment by mjewell** [comment]
Still can't think of anything, but you can take some further steps to debug it. First thing is obviously to make sure you haven't made any changes to anything sequelize related. After that...

You can try running it locally but setting that env variable, something like `NODE_ENV=production POSTGRES_DB_URL=postgres://root:@localhost/react_webpack_node_production sequelize db:migrate`

If that looks like it's working fine then that means it does appear to be reading the config correctly. You can try changing the postgres sequelize_config.js to use the env variable directly, as shown [here](https://github.com/sequelize/cli#user-content-configuration-connection-environment-variable), using the `url` property instead of `use_env_variable`. You can also try putting `console.log(process.env.POSTGRES_DB_URL)` at the top of the sequelize config and see what value it is seeing there.

**Comment by kuiro5** [comment]
Having same issue on fresh clone.

**Comment by iamademar** [comment]
@coderjonny Were you able to find a solution?

**Comment by iamademar** [comment]
Figured it out. On server/db/postgres/sequelize_config.js:

You should remove username, password, database and host on the production hash.

From this hash:

`
module.exports = {
  development: {
    username: process.env.PGUSER || 'root',
    password: null,
    database: 'react_webpack_node_development',
    host: '127.0.0.1',
    dialect: 'postgres'
  },
  test: {
    username: process.env.PGUSER || 'root',
    password: null,
    database: 'react_webpack_node_test',
    host: '127.0.0.1',
    dialect: 'postgres'
  },
  production: {
    use_env_variable: 'POSTGRES_DB_URL',
    username: process.env.PGUSER || 'root',
    password: null,
    database: 'react_webpack_node_production',
    host: '127.0.0.1',
    dialect: 'postgres'
  }
`

It should look something like this:

`
module.exports = {
  development: {
    username: process.env.PGUSER || 'root',
    password: null,
    database: 'react_webpack_node_development',
    host: '127.0.0.1',
    dialect: 'postgres'
  },
  test: {
    username: process.env.PGUSER || 'root',
    password: null,
    database: 'react_webpack_node_test',
    host: '127.0.0.1',
    dialect: 'postgres'
  },
  production: {
    use_env_variable: 'POSTGRES_DB_URL',
    dialect: 'postgres'
  }

`

Make sure the POSTGRES_DB_URL is the correct Heroku ENV variable for your postgres db url on heroku.

Hopefully this answer saves you time. :)
