### ISSUE TITLE
"active" class-name on Navigation.jsx Links

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#233]
"active" class-name on Navigation Links `activeClassName={cx('active')}` not changing/updating when switching routes.

anybody else have this issue or know cause/fix?

started working after removing all traces of user/dispatch/login/logout, but not sure why.

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it. Moreover, the code has changed quite a lot since this issue was opened.
If you still experience this or have an issue, please comment here or open a new one.
