### ISSUE TITLE
Why is server.js exposed?

### ISSUE THREAD

**Issue by darkyen** [reactGo/reactGo#236]
https://react-webpack-node.herokuapp.com/assets/server.js 

Exposes the server.js, why?

**Comment by bottledsmoke** [comment]
The server files are never sent to the client. What you are looking at is the result of webpack using app/server.jsx as an entry point and bundling the server-side rendering code. This file is sent as a response to initial requests to the server and rendered out.

**Comment by darkyen** [comment]
I understand it is potentially harmless, just wondering why is it openly hosted :S
