### ISSUE TITLE
Bundle splitting

### ISSUE THREAD

**Issue by IljaDaderko** [reactGo/reactGo#274]
My project is getting relatively big for one bundle, hence I wanted to look into bundle splitting, i.e. using separate bundles for separate pages, If anyone could kickstart me in the right direction, I can work a pull request for this if needed.

**Comment by slavab89** [comment]
There is this page https://webpack.github.io/docs/code-splitting.html which i didnt try.
There is also a plugin that looks promising https://webpack.github.io/docs/list-of-plugins.html#dllplugin which as i understood it puts all your vendor modules in a different file.

On this note, i also wanted to ask you about your build times, how are they? initial build and reloading?

**Comment by IljaDaderko** [comment]
@slavab89 builds take up 7405ms and 7552ms seconds for both build stages, and rebuilding is usually quick. I will look into links you provided, thank you.
