### ISSUE TITLE
Bundle splitting

### ISSUE THREAD

**Issue by IljaDaderko** [reactGo/reactGo#280]
I believe webpack is set up to do bundle splitting, but I can't figure out whats the correct way to do that I believe this bit is responsible for the functionality: https://github.com/choonkending/react-webpack-node/blob/master/webpack/webpack.config.prod.js#L70

Is it the only place where I need to specify my rautes and bundle names? and it should work? or Do I need to import additional things?

**Comment by psimyn** [comment]
just that should work, but multiple entry points means including the entry points in different templates, which I don't think the boilerplate is organised for currently.

Are you wanting to split for different pages, or to keep bundle size small? If you are doing single page with react router, but you want to lazily load bundles then there is a few webpack config options.

**Comment by IljaDaderko** [comment]
@psimyn Essentially split for different pages, So I don't need to load code that is not used by that specific page. This will be first time I attempt this, would really appreciate links to some in depth sources (not webpack docs, I find them hard to understand)

**Comment by psimyn** [comment]
hahahaha you are not alone in finding the webpack docs hard to understand. This great presentation from sokra has some good examples & explanations of async and split options: https://sokra.github.io/slides/frontend-optimize
They aren't full examples, but explain stuff enough that you can google toward answers.

If your separate pages are fully separate html files then the multi-entry point method is the way to go (but I'll need link or code example to help more for this).

If you keep react-router multi pages (e.g. you don't want to load 'login' code on the 'topics' page), you can either use a lazy module loader (untested [example](https://github.com/NekR/async-module-loader)) _or_ use `System.import` from webpack 2; this is a good example of that: http://moduscreate.com/code-splitting-for-react-router-with-es6-imports/

**Comment by githubjosh** [comment]
i just started down this path. An example using using the About page:

In routes.jsx:
`return (
    <Route path="/" component={App}>
      <Route
        path="about"
        getComponent={(location, callback) => {
          require.ensure([], function (require) {
            callback(null, About);
          });
        }}
      />
    </Route>
  );`

In webpack.config.prod.js:
`entry: {
      about: "pages/About.jsx",
      app: "pages/App.jsx"
    },
    plugins: [
      new CommonsChunkPlugin("app", "app.js")
    ],`

In headAssets.js:
`const scriptAssets = () => {
  const scripts = [{src: "assets/app.js", type: "text/javascript"}];
  return scripts;
};
export const script = scriptAssets();`

And Page.jsx:
`<Helmet title={title} link={link} meta={meta} script={script} />`

And lastly in About.jsx
`pageScripts() {
    return [{src: "assets/about.js", type: "text/javascript"}];
  }`

Hope that helps :)

**Comment by slavab89** [comment]
We have several PR's that address code splitting https://github.com/reactGo/reactGo/pull/919 https://github.com/reactGo/reactGo/pull/841 and some more.  The basic layout for code splitting is already in master branch. If you still have a specific issue with this, please open a new issue.
