### ISSUE TITLE
Async Fetching Data w/ Props.params Query

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#281]
Say you have a component that just displays a single **TopicItem** (../containers/topicItem.jsx), and you want to async fetch the data for that item [using a URL-Query from _props.params.topicID_] similarly to how it's done in `Vote.jsx`:

``` javascript
   static need = [  // eslint-disable-line
      fetchTopics
    ]
```

How would you pass a query-ID to a similar "_fetchTopic_" to make the request like so?

``` javascript
export function fetchTopic(id) {
  return {
    type: types.GET_TOPIC,
    promise: makeTopicRequest('get', id)
  };
}
```

**Noticed that this same question has been asked a number of times and in several different places... Going to attempt to document a simple solution below, as none of the other discussions provide a clear cut answer as to how they "got it working."

**Comment by choonkending** [comment]
Good question!

Our [client](https://github.com/choonkending/react-webpack-node/blob/master/app/client.jsx#L35) and [server](https://github.com/choonkending/react-webpack-node/blob/master/app/server.jsx#L97) both run the [preRenderMiddleware](https://github.com/choonkending/react-webpack-node/blob/master/app/middlewares/preRenderMiddleware.js#L15) which calls all the `need` functions from components.

So your `fetchTopic` function should be able to get the parameter if you can pass in the id you need - I haven't tested this myself.

Let me know how that goes!

**Comment by slavab89** [comment]
Take a look at this issue as well https://github.com/choonkending/react-webpack-node/issues/268 because they talk there on the same thing i believe :)

**Comment by yowakita** [comment]
I have been having trouble with this same issue, I am not able to pass in a parameter and have the fetch return anything. If you were to put 
```static need = [
fetchTopics(0) // First index, later passed in as param to route/controller
]```
and change the fetchTopics to 
```
// Fetch posts logic
export function fetchTopics(id) {
  return {
    type: types.GET_TOPICS,
    promise: makeTopicRequest('get', id)
  };
}
```

you get an error  `need is not a function`

Any thoughts? Maybe I am approaching this incorrectly?

**Comment by choonkending** [comment]
@yowakita Thanks for pointing that out. 

I think a quick fix for this would be to make fetchTopics in the Vote.jsx (or whatever component) you have to return a function.

```javascript
static need = [ fetchTopics:  (id) => () => fetchTopics(id) ]
```

I have not tested the above yet. We might have to change how our middleware works if that approach doesn't work. Would you like to try out a solution like the above? 

I'm a bit late on responding to issues as I'm trying to juggle with between work and trying to get my offline understanding up to speed.

Happy to hop in and help if you hit more roadblocks. (Kudos to everyone who highlighted this issue prior to this)

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it. Moreover, the code has changed quite a lot since this issue was opened.
If you still experience this or have an issue, please comment here or open a new one
