### ISSUE TITLE
Flash Of Unstyled Content (FOUC) in Dev?

### ISSUE THREAD

**Issue by kenjim83** [reactGo/reactGo#289]
First off, thanks so much for creating this starter kit, it looks awesome!

I booted it up in dev and noticed every page refresh shows about 500ms of unstyled HTML.  Is anyone else experiencing this?  Any tips to prevent this?

**Comment by ZeroCho** [comment]
I also experience this but until now I dont take it serious because it only happens in dev mod.

I think it's because of inline styles that rendered on client. Server cannot handle css unless you use webpack-isomorphic-tools package. This package is used in react-redux-isomorphic-app by erikras.

**Comment by jrodl3r** [comment]
Yup, only happens in DEV as @ZeroCho explained. Even with a massive background-image, zero hiccups w/ rendering on Heroku. Really smooth w/ `<ReactCSSTransitionGroup>` too, was thinking of creating a PR for that, and also to add `react-router-scroll` (so pages don't load 1/2 way scrolled down).

This is more on the rookie side-of-things, but also beware of default State, sometimes you'll see a flicker of text and realize you just need to tweak your display logic a little bit to keep it clean until a fetch completes, or whatever..

**Comment by stanleycyang** [comment]
This is happening to me in production. Any reason why?

**Comment by rclmenezes** [comment]
This happens to me in production mode as well.

**Comment by rclmenezes** [comment]
Ah, I've identified my issue. If you run `npm run start` after running `npm run dev`, your files in public/assets will be still be in dev mode.

Other webpack noobies like me might have similar problems in the future. Perhaps we can make webpack build in different folders within `public` depending on the stage? So `webpack.config.prod.js` will build in `public/prod/assets` and `webpack.config.dev.js` build in `public/dev/assets`?

**Comment by ZeroCho** [comment]
@rclmenezes This makes sense.
@choonkending This can be solved by adding `npm prestart` script

**Comment by choonkending** [comment]
> Alternatively, could we make npm run start build prior to actually starting?
I like this idea! Sorry for the lack of clearer documentation - we're working towards a better + cleaner repository so hopefully a lot of the configuration will become simpler over time.

> This can be solved by adding `npm prestart` script

Did not know this even existed lol. Sure I think we should add that in!

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it. Moreover, the code has changed quite a lot since this issue was opened.
If you still experience this or have an issue, please comment here or open a new one
