### ISSUE TITLE
Bringing SCSS 

### ISSUE THREAD

**Issue by ramakay** [reactGo/reactGo#332]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Question
How Can I bring back SCSS Support.

I understand that the boilerplate now favors CSS Modules instead of SCSS. But i wish to go back to the SCSS layer.

**Comment by choonkending** [comment]
@ramakay Thanks for raising this issue. Apologies for the late reply. That's a valid concern if you are already using scss in your project.

You can bring back scss support by adding a `sass-loader` into your webpack config

```javascript
npm install sass-loader node-sass webpack
```

which would effectively replace [this bit](https://github.com/choonkending/react-webpack-node/blob/master/webpack/webpack.config.prod.js#L41).

Read more [here](https://github.com/jtangelder/sass-loader#sass-loader-for-webpack) about to configure sass on the sass-loader repo.

**Comment by ramakay** [comment]
Thanks 👍  Interestingly here we are a month later and I like CSS Modules already ;)

**Comment by donpinkus** [comment]
Made a repo that does it: https://github.com/donpinkus/reactgo-scss
