### ISSUE TITLE
Improve Pagespeed score

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#371]
### Description
- Type:  Enhancement | Question
- Related Issue: #278 
## Enhancement

**Reason to enhance/problem with existing solution**
Our current score is [ 75/100](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Freact-webpack-node.herokuapp.com%2F&tab=mobile) (pointed out by @caranicas ). We can definitely look into improving the score with the suggestions by Google. 

Performance is key!

**Comment by caranicas** [comment]
yeah I totally meant to make a general issue for this.

I've been playing around with it but 


```
res.status(200).send(`
          <!doctype html>
          <html ${header.htmlAttributes.toString()}>
            <head>
              ${header.title.toString()}
              ${header.meta.toString()}
 ~~ ${header.link.toString()}~~
            </head>
            <body>
              <div id="app">${componentHTML}</div>
              <script>window.__INITIAL_STATE__ = ${JSON.stringify(initialState)};</script>
              ${analtyicsScript}
              <script type="text/javascript" charset="utf-8" src="/assets/app.js"></script>
              ${header.link.toString()}
            </body>
          </html>
        `);
```

**Comment by caranicas** [comment]
yeah, I meant to make this issue. been looking in to it. need to get a bit more familiar with `react-helmet`

**Comment by caranicas** [comment]
ok, so helmet lumps all links together. It has a separate section for css, but it seems to be for page level styles blocks, not sheets themselves. 

I tried moving `${header.link.toString()}` to further down on the page, to the very bottom of the body, but it doesn't affect the page speed score. 

```
res.status(200).send(`
          <!doctype html>
          <html ${header.htmlAttributes.toString()}>
            <head>
              ${header.title.toString()}
              ${header.meta.toString()}
            </head>
            <body>
              <div id="app">${componentHTML}</div>
              <script>window.__INITIAL_STATE__ = ${JSON.stringify(initialState)};</script>
              <div class="eXtra"></div>
              ${analtyicsScript}
              <script type="text/javascript" charset="utf-8" src="/assets/app.js"></script>
              ${header.link.toString()}
            </body>
          </html>
        `);
```

running locally through ngrok I also get this issue 

> Remove render-blocking JavaScript:
http://26ed0ae6.ngrok.io/assets/app.js

The Heroku build doesn't flag this, but that is also at the bottom of the page, and isn't render blocking anything as far as I can tell.

**Comment by jrodl3r** [comment]
removed CSS @font-import, and now inline like so:

```javascript
<head>
  ${header.title.toString()}
  ${header.meta.toString()}
  <link href="//fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet" type="text/css">
  ${header.link.toString()}
</head>
```

there can be a font-rendering flicker (esp. in DEV-mode), and feels cleaner, more explicit.

**Comment by choonkending** [comment]
Nice investigation!

I think the `link` should still be in the `<head>` tag. 

However, we __**could**__ inline our critical css by running our page through a `critical` tool specified [here](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery), and then _defer_ loading through the function provided in the example. Then we could potentially remove render blocking external stylesheets loading from the `link`s config for helmet.
