### ISSUE TITLE
Prioritzation

### ISSUE THREAD

**Issue by caranicas** [reactGo/reactGo#385]
So it seems like  we are going to go ahead with #372, and I am all for it. So how do we get this to a point where we can start to make that transition?

There are still some outstanding pull requests surrounding refactoring and file organization, There has been a lot of discussion around them, but  little movement recently. I am not sure if #260 and #269,#270 and #272 are at odds with one another, specifically #269 and #260, so I am unsure of where I should focus my efforts.

@choonkending if you could create a todo list of things that you need to like to see happen before we make the move to an ORG then I can focus my efforts on cleaning up the PRs and doing some of the work to get us to that point. I am in the middle of job interviews right now so I have quite a few spare cycles, and to be honest this project is more compelling than my current personal project.

**Comment by choonkending** [comment]
Apologies for the late reply! And thanks for summarising the PRs and outstanding issues.

In terms of refactoring and file organization, I would like to get #260 as it is more in line with what I envision and is a result of multiple discussions with @psimyn 

As for #269, #270, and #272, I am planning to refer to them as we refactor them and close them.  The PRs are good but dependent on each other to be merged in order. Apart from them, #272 will get changed once https://github.com/choonkending/react-webpack-node/pull/323 is merged in, so I think it's safe to close them for now. 

> if you could create a todo list of things that you need to like to see happen before we make the move to an ORG then I can focus my efforts on cleaning up the PRs and doing some of the work to get us to that point

Sure. I'll list the todo list here:
- [ ] Get https://github.com/choonkending/react-webpack-node/pull/384 enzyme support merged
- [ ] Get #323 merged for CSS next support
- [ ] Create a separate branch [__**release-stateless-2.0**__](https://github.com/choonkending/react-webpack-node/compare/release-stateless-2.0) that cleans it up DB config.
- [ ] Merge all the greenkeeper PR's hahaha.

Let me know if I'm missing anything. We would then need to decide what repositories to create!

> I am in the middle of job interviews right now so I have quite a few spare cycles, and to be honest this project is more compelling than my current personal project.

Thanks a lot! Also good luck with your interviews 🙏 !

**Comment by choonkending** [comment]
I believe we have a project wall [here](https://github.com/reactGo/reactGo/projects/1) which makes it easier to prioritise now. Closing this!
