### ISSUE TITLE
ExtractTextPlugin needs allChunks: true

### ISSUE THREAD

**Issue by ZeroCho** [reactGo/reactGo#414]
Your project doesn't have any problem itself. But if somebody extends yours, attaches some modules, or splits the code for lazy loading, a problem happens.

I tried to use React-router dynamic routing. So I split the code, made several chunks. Then, I faced the server problem which says
`window is not defined`
This is because of style-loader on the server. ExtractTextPlugin only extracts from initial chunks, not the others. So the other chunks are handled by style-loader which doesn't support server side css.

I found out the solution and it is to add **allChunks: true** which extracts from all chunks.
`new ExtractTextPlugin('styles/main.css', { allChunks: true });`
This is what [react-redux-hot-example](https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/prod.config.js#L59) does too.

There is another solution which uses webpack-isomorphic-tools, but this totally changes the structure of this project.

**Comment by choonkending** [comment]
Thanks for this @ZeroCho ! Would you like to create a PR for this?

**Comment by choonkending** [comment]
👍 Champion!
