### ISSUE TITLE
Errors when db set to 'NONE'

### ISSUE THREAD

**Issue by jgentes** [reactGo/reactGo#419]
I set:

`defaultExport.DB_TYPE = DB_TYPES.NONE;`

and when I run 'npm run dev' I get:
```
Attempted to use '(de)serialize User' but DB type 'NONE' doesn't support it
Attempted to use 'passport-local' but DB type 'NONE' doesn't support it
Attempted to use 'passport-google-oauth' but DB type 'NONE' doesn't support it
module.js:327
    throw err;
    ^

Error: Cannot find module './webpack.config.dev-client'
```

**Comment by ZeroCho** [comment]
remove `passportConfig();` from /server/index.js.
@choonkending we need to remove this when DB type is NONE.

**Comment by jgentes** [comment]
Actually I still ended up getting the `Error: Cannot find module './webpack.config.dev-client'`

As it turns out, line 24 of server/index.js has the incorrect path for that file. It should be:

`const webpackDevConfig = require('../webpack/webpack.config.dev-client');`

Once I made that change, there was no need to remove passportConfig();

**Comment by choonkending** [comment]
@jgentes Thanks for pointing out! I have fixed this here https://github.com/reactGo/reactGo/blob/master/server/index.js#L24.
