### ISSUE TITLE
[Help] First request with large object

### ISSUE THREAD

**Issue by slavab89** [reactGo/reactGo#426]
So i have a somewhat different question and i would really like for your help.
Me app needs to show some data in a table on the page, that data is about 2.5MB large. The data consists of object and the table shows some of the properties of the object. There is about 1000 such objects.
The data is needed before the page loads for the user so i've used the const need of the component.

Now, the problem that i'm facing.
Every time i perform a full refresh, the server.jsx calls the need function that fires an event to the server side using axios. The server calls some distant API to receive back the data (takes less than 1 second). 
The amount of time between receiving the initial byte of data until all the data is received on the server.jsx side (right after the function of preRenderMiddleware) moves between 10-60 seconds. I've added console log before and after that function.

Moreover, i have a button on the same page that performs the same flow of action just without the server.jsx side (cause its a client request). That requests ends in about 1 second all the time!

I have no idea what is causing this behaviour.
I'm using 'request' module to call the distant API for the data and and listened for the 'response' and 'end' events of that call and the difference between them is 10-60 seconds when i'm in the flow of a full page refresh and about 1 seconds when i'm in a client side action.

If anyone has an idea what can cause this or what should i try then please please help!

**Comment by jrodl3r** [comment]
not 100%, but possible the delay has to do with SSR...

[Speed up Server Side Rendering - Sasha Aickin](https://www.youtube.com/watch?v=x-puVr1L2Vg)

**Comment by slavab89** [comment]
Thanks for the video! It actually helped me to try something else.
The app.js file (the whole client side application) on my end is about 4.4mb.
I've tried to do the API call on componentDidMount function so that i'll see the UI and then a request would be made. That request seems to take about 6 seconds on average. That's how long it takes to download the data from the remote server. 

So i guess there is no much i can do about those 6 seconds to download the data =[
I could maybe download it in several parts or something, so that i'll start showing the user something while all the other data loads and downloads in the meantime.

**Comment by jrodl3r** [comment]
I would suggest you setup a system for "polling" your data on the server. Basically, when you request the data anytime after initial-load, check the timestamp, or array length, etc. (anything to determine if you actually need to send the full dataset, or if that's is a pointless exchange because the data is already fresh in the browser's cache, etc.)
