### ISSUE TITLE
Add Why Did you Update for Dev debugging for performance

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#430]
## Enhancement

**Suggested enhancement**
https://github.com/garbles/why-did-you-update
- We can then easily find where the performance bottlenecks are.

**Pros**
More awareness of performance

**Comment by ZeroCho** [comment]
I installed that package and used that just before. It says that we can avoid re-render in many things. It took a lot of time to fix all problems. Maybe we need consider reusing ImmutableJS.

**Comment by choonkending** [comment]
LOL I just read this post last night! Was a great read!

I think as a first step it's an _enabler_ to at least know where the problems are. At the very least, I'm hoping for [release 2.0](https://github.com/reactGo/reactGo/pull/406) to be performant and free from unneeded re-rendering. We can then work on slowly removing those in the example apps. 

Perhaps it should be an `opt-in` toggle instead? We don't want to flood the console with warnings, might be hard to work on.

`npm run dev:pref` perhaps, which disables `redux-logger` and only shows this warning.

**Comment by ZeroCho** [comment]
One suggested ways to toggle [Link](https://github.com/garbles/why-did-you-update/issues/20)

**Comment by ZeroCho** [comment]
why-did-you-update package doesn't work well with recent react version 15.3.0

**Comment by slavab89** [comment]
So the original package has been deprecated. There is a fork at https://github.com/maicki/why-did-you-update
When i used it, it was quite weird. It said that i can avoid re-render yet i didnt see any place that actually caused the re-rendering 😢  Maybe the re-render was caused at one of the parents. In a small project (such as this boilerplate) it should be possible to address this, however if might take some time and not prove as easy as we would want

**Comment by GGAlanSmithee** [comment]
Another somewhat related note. When we introduce `react-hot-loader@3` we can use `PureComponent` to avoid "hidden" re-renders.
