### ISSUE TITLE
Broke test website

### ISSUE THREAD

**Issue by Cretezy** [reactGo/reactGo#443]
Note: This is just a template, so feel free to use/remove the unnecessary things
### Description
- Type: Bug

---
## Bug

**Expected Behavior**

Enter `<script>alert(1)</script>` as a topic to vote on and have it show up in the list.

**Actual Behavior**

The string wasn't escaped and the site crashes.

**Steps to Reproduce**

Enter `<script>alert(1)</script>` as topic to vote on.

**Comment by caranicas** [comment]
can you be a bit more specific?  Where did you put that code?

**Comment by ZeroCho** [comment]
He meant he put that code in Vote box as a new topic in website. I found that the string is not escaped but just disappear

**Comment by caranicas** [comment]
cool. I went in and edited it to make a bit more clear.
