### ISSUE TITLE
Webpack dev-client and dev-server

### ISSUE THREAD

**Issue by thientran1707** [reactGo/reactGo#453]
## Question

I am curious why we have both dev-client and dev-server webpack config file.

**Comment by ZeroCho** [comment]
You mean why reactGo separate two files? It is because webpack.config.dev-client.js is required at server/index.js, whereas webpack.config.dev-server.js and webpack.config.prod.js aren't.

**Comment by jrodl3r** [comment]
This is the "isomorphic" nature of things, which can take a little getting used to (especially when you run into issues with why something runs on the client, but blows up on the server [tip: use DefinePlugin FLAGS]).

The "Client" config is built to be run in the client/browser/DOM/etc. The "Server" is built and executed on the server.  There is a PROD Client too, but it's all in the same config file along with the SSR/Server config.

First project I've worked w/ webpack, so correct me if I'm wrong, anybody 🍻

**Comment by alex-shamshurin** [comment]
What about universal webpack? It's a little annoying to uptake 2-3 files.

**Comment by iKonrad** [comment]
Yeah I'm having a hard time trying to include few npm modules in webpack.
Should the css/js files be included in the 'entry' section in webpack config? If so, in which one?
Or maybe through the require() in App.jsx?
I've tried to require few css files (with style!css! flags), but I'm getting 'window' is not defined error.

Anyone got the same issue?

**Comment by alex-shamshurin** [comment]
I found this config to be one of the best but workflow is not ideal as it is in https://github.com/kriasoft/react-starter-kit which has browserSync and many other things and only one webpack config. It even allows hot reloading on stateless components.

**Comment by choonkending** [comment]
Thanks for that @alex-shamshurin 

I do agree with
> It's a little annoying to update 2-3 files.

That's kind of on my to do list to reduce the complexity of the configs. :(

**Comment by alex-shamshurin** [comment]
To avoid problem with 'window' the best solution is isomorphic-style-loader, like this

```
 {
        test: /\.styl$/,
        loader: 'isomorphic-style-loader!css?modules&importLoaders=1&localIdentName=[path][local]___[hash:base64:5]!' +
        'stylus?paths[]=node_modules&include css&resolve url'
      },
```

**Comment by alex-shamshurin** [comment]
@choonkending Let's then merge it with https://github.com/kriasoft/react-starter-kit config. Do try a workflow which it provides. Everything is hot reloaded.

**Comment by jrodl3r** [comment]
this thread is out of control 🙈

**Comment by slavab89** [comment]
We're cleaning the project of stale issues therefore i'm closing this. The different files were combined to one at https://github.com/reactGo/reactGo/pull/822
