### ISSUE TITLE
Nodemon App Crashed

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#455]
Was wondering if anyone else is getting DEV webpack / nodemon crashes?

Error:
```
webpack building...
webpack built 31f1b29fc8ba6603a593 in 515ms
sh: line 1: 10880 Abort trap: 6           npm run babel-node -- server/index.js
[nodemon] app crashed - waiting for file changes before starting...
```

I recently upgraded node to 6.4.0, not sure if this is the culprit...

**Comment by choonkending** [comment]
Thanks! We recently bumped up the version of nodemon. I'll have a check on
the train!

**Comment by choonkending** [comment]
I haven't bumped my node version up to `6.4.0`, but I've tested on versions:
- 5
- 6.2

I'll install `6.4.`once I get a decent connection. So far nodemon repo doesn't seem to be reporting any version related errors.

Can you try wiping your `node_modules` directory and `npm install` again? :(

**Comment by jrodl3r** [comment]
think that did the trick... too many one-off branches! Thx buddy :)
