### ISSUE TITLE
Change title on each page on route

### ISSUE THREAD

**Issue by mateeyow** [reactGo/reactGo#457]
### Description
- Type:  Question
## Question

**How can I change the title on each page for universal app. So for example I would like `About.jsx` to have `About | React Go` title, `Dashboard.jsx` to have `Dashboard | React Go` and so on.. I would also like to make use of titleTemplate**

**Comment by ZeroCho** [comment]
You can use react-helmet. This is already included in this package. Just read its documentation.

**Comment by mateeyow** [comment]
Yes, but adding `<Helmet title='About' />` to About.jsx will change all of the title to **About**

**Comment by ZeroCho** [comment]
There is an another option defaultTitle.
<Helmet title='About' defaultTitle=' | React Go'/>

**Comment by mateeyow** [comment]
Doesn't really do anything. Problem here is that if you add `<Helmet ... />` code to any of the **containers** and when you go to that page the whole title will be replaced. So when I go to `/about` with `<Helmet title="About />` the title will change to **About** but going back to dashboard the title will still be **About**

**Comment by ZeroCho** [comment]
You should also put Helmet in Dashboard such like <Helmet title='Dashboard' />

**Comment by mateeyow** [comment]
Done didn't work. Have you tried it yourself?

**Comment by ZeroCho** [comment]
Im running my own blog based on this package and everything goes fine.
I'll tell you from basic.

First you have to add
`<Helmet defaultTitle=" | React Go />`
in app/containers/App.jsx

Second you add Helmet in both About and Dashboard
```
<Helmet title="About" />
<Helmet title="Dashboard" />
```

**Comment by mateeyow** [comment]
Yeah tried that one already but it really overrides the `Meta.jsx` headers.

**Comment by ZeroCho** [comment]
Meta.jsx is not related with client side dynamic title now. So if you want to use Helmet in client-side, you should make Meta.jsx totally different from current Meta.jsx

**Comment by mateeyow** [comment]
Ah! I thought it was somehow connected with the client. I'm still new to this universal app thing. Thanks for the clarification. You've been a great help!

**Comment by choonkending** [comment]
@mateeyow @ZeroCho Thanks for the great discussion! (And also for the quick response to giving a good solution!)

Given that there is a bit of confusion surrounding this, I think that it's a good indication that we should perhaps consider refactoring the behaviour of our `<helmet>`.

Perhaps:
- Create a Higher Order Component with `<Helmet title={props.title} />` and the Composed Component.
- Refactor Meta.jsx's logic to be within server.jsx so that it is less confusing. 

I will propose a solution here and see what you guys think!

**Comment by ZeroCho** [comment]
@choonkending Yes. This is somewhat confusing because Meta.jsx is in the client directory. Other bolierplate projects use **shared** directory for shared components. Any thoughts about this?

**Comment by choonkending** [comment]
@ZeroCho Apart from server.jsx and client.jsx I think all components should be shared on client and server - or at least that's where we should aim. I like having shared components, but my concern with having **shared** as a folder might make it even more confusing when creating components, particularly when we have to decide whether to put it in 1 of 3 folders. (Correct me if my understanding is wrong).

On a separate note, here's an initial spike - I've seen this used and I think it's a good starting point. This is to only handle client side, will hopefully remove Meta.jsx once I get this approach right.

[Code here](https://github.com/reactGo/reactGo/compare/get-betta-with-meta)

**Comment by ZeroCho** [comment]
@choonkending Looks good to me. Just I have one question. Is it good practice to wrap Container by Component? The Page component wraps Vote Container now.

**Comment by caranicas** [comment]
I agree with @choonkending I don't think a shared folder is a good idea, but maybe a more detailed read me about meta information is in order.

**Comment by brtw** [comment]
@ZeroCho Looking at the code in your solution, I'm having a hard time replicating what you did. I'm not so sure where replaceMeta() and filterTags() are defined in your meta.jsx file. Also unsure about  makeHeader() in server.js. I am looking to accomplish exactly what you have done for your SEO for my site and would love any direction or help you might have to suggest!

Thanks.

As an overall comment, @choonkending @caranicas; I saw you were trying for a page speed score enhancement. I think that would be a good move, but I would also suggest that we do get an enhancement for improving the seo of this project. I am proposing something where we can specify route-based title and meta tags as I think was proposed above. I'd be happy to contribute to a solution if I end up figuring this out. Are PRs currently addressing this that I have missed?

**Comment by ZeroCho** [comment]
@brtw oh, replaceMeta and filterTags are not defined in my meta.jsx. It's in the separate file. replaceMeta is to change meta tag for each route and filterTags are for making meta description, which filters tags from the posts. makeHeader function uses both replaceMeta and filterTags function to make meta, link, script tags

**Comment by choonkending** [comment]
Totally agree with seo improvement. I have a branch for meta tags coming up
soon but won't have time to have it merged till next week :(

**Comment by brtw** [comment]
@ZeroCho Thanks! , @choonkending Great! I have plenty to be doing in my project till next week. I can wait for your merge and focus my efforts on some other features in my project. Does your branch support per-route or per-pathname titles and meta-properties?

**Comment by choonkending** [comment]
Yes it will, you will have to specify it. Look at the comparision [here](https://github.com/reactGo/reactGo/compare/get-betta-with-meta), still some stuff to clean up for production - but it works on dev.

Need to find a bunker somewhere and finish this off next week (after Tuesday).

**Comment by stanleycyang** [comment]
@choonkending Did you ever merge this? I tested it out and I was getting FOUC on page switches

**Comment by brtw** [comment]
@choonkending I'm considering implementing the proposed [code](https://github.com/reactGo/reactGo/compare/get-betta-with-meta) to get a jump on improving the SEO of my project. Did you plan on changing anything before merging or is this good to go?

**Comment by choonkending** [comment]
Hey there are still some changes needed for it:
- meta tag changes
- (perhaps) using HTML loader?

I'll list more down later. Sorry for the delay mate, just been bogged down
recently. I'll whip something out soon

**Comment by choonkending** [comment]
Hey guys, a quick update,

**Comment by choonkending** [comment]
I'll create the PR once I fix the remaining issues and hopefully we can get some SEO juice!

**Comment by choonkending** [comment]
https://github.com/reactGo/reactGo/pull/675

Will merge tomorrow at noon sharp. Haha. Sorry I took so long.

**Comment by choonkending** [comment]
Merged! Closing now!

**Comment by choonkending** [comment]
Please re-open if there's still an issue!
