### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by subpublic** [reactGo/reactGo#459]
## Bug

When running `npm run dev` I'm getting

```
import express from 'express';
^^^^^^
SyntaxError: Unexpected token import

```

---

Though it works fine running `npm run start`.
I'm finding some forums talking about a babel issue (babel --presets es2015) but I cant understand why it only happens with dev.
Running Node v6.2.2. npm 3.8.9.

Anybody else?

**Comment by jrodl3r** [comment]
try deleting `/node_modules` and then `npm install` again?

**Comment by subpublic** [comment]
Yes, and I have cloned the whole repo again, but didn't help.
I'm thinking it might have something to do with babel 6 (presets es2015). Or can it be that I dont have babel installed globally?

**Comment by ZeroCho** [comment]
Try install babel and babel-related packages globally. Maybe it will fix this problem.

**Comment by caranicas** [comment]
@subpublic any movement on this?

**Comment by subpublic** [comment]
@caranicas Nope, I tried reinstalling both node and npm but did nothing good so unfortunately had to give up.

**Comment by caranicas** [comment]
did you try installing babel globally? Another option (a long shot) would be to try running it in chrome canary? That might have support for `import`. It wouldn't solve your porblem, but it would give you a way to get started.

**Comment by slavab89** [comment]
We're cleaning the project of stale issues therefore i'm closing this. The codebase has changed quite a lot since this issue was opened.
If you still have any issue, please comment here or open a new issue.
