### ISSUE TITLE
get request with axios before page load  404 . But Server dont even recieves request

### ISSUE THREAD

**Issue by rickcoub** [reactGo/reactGo#471]
Cant perform get request with axios before page load (for fetching data from server) Browser log shows 404 Not Found. But Server dont even recieves request. But if i use any POST request instead GET, it is working as expected. What Am i doing wrong?
I'm trying somethin like

```
class some extends Component {
  componentDidMount() {
    axios.get('/user/userreqs/req')
    .then(function (response) {
      console.log(response);
    })
    .catch(function (error) {
       console.log('err sdfsdffsd');
    });
  }

```

Is GET request requires setting action types for it?

**Comment by slavab89** [comment]
We're cleaning the project of stale issues therefore i'm closing this. If you still have any issue, please comment here or open a new issue.

Regarding your question, verify that you have `/user/userreqs/req` route defined on the server side, for GET/POST or both.

**Comment by Sphinxs** [comment]
@slavab89 , I have checked and I still receiving the same error that @rickcoub  had received.
