### ISSUE TITLE
Modernizr

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#473]
Trying to detect `touchevents` using Modernizr in `App.jsx` to roll the appropriate DnD backend...

```javascript
if (__DEVCLIENT__) {
  Modernizr = require('./external/modernizr.js');
}
App = DragDropContext(Modernizr && Modernizr.touchevents ? TouchBackend : HTML5Backend)(App);
```

Guessing this has something to do with SSR, because logs on the server/build/initial-pageload are `undefined` but if I ping `Modernizr` in the browser console post-pageload it shows the object with the `touchevents` key as true/false.

Current workaround is just rolling `TouchBackend({ enableMouseEvents: true })` but I'll post a code sample - this would be a much more desirable approach (*if possible).

Honestly, I don't think this is going to be possible because of how `App.jsx` is processed (as part of the initial SSR payload) and executed (long before `window` / `document` ever show up).

Would love to hear someone tell me I'm wrong on that! 🍻 

_No luck here:_
- https://github.com/peerigon/modernizr-loader
- https://github.com/alexpalombaro/modernizr-webpack-plugin

_Issues:_
- https://github.com/Modernizr/Modernizr/issues/1597
- http://stackoverflow.com/questions/26229323/webpack-and-modernizr-causes-typeerror-document-is-undefined-error

**Comment by choonkending** [comment]
I haven't used Modernzr with this repo and on SSR before. Sounds like an SSR issue.

If you have more sample code (or a branch up), maybe we could have a look and try to debug this further.

**Comment by jrodl3r** [comment]
Ok, solution was to use this webpack loader - [peerigon/modernizr-loader](http://github.com/peerigon/modernizr-loader)

But the trick is to use `webpack.DefinePlugin(){...}` to control how it all works in `App.jsx`:

```javascript
if (__DEVCLIENT__ || __PRODCLIENT__) {
  const Modernizr = require('modernizr');
  App = DragDropContext(Modernizr.touchevents ? TouchBackend : HTML5Backend)(App);
} else {
  App = DragDropContext(TouchBackend({ enableMouseEvents: true }))(App);
}
```

just need to add another flag for PROD webpack config:
```javascript
new webpack.DefinePlugin({
  __PRODCLIENT__: true, // false on SSR

}),
```
