### ISSUE TITLE
DeprecationWarning: Mongoose: mpromise (non-breaking)

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#477]
On latest Node (6.5.0) + MongoDB/Mongoose:

» webpack building...
» webpack built ff1021efcf55585d47d0 in 6985ms
» (node:1417) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

» webpack building...
» webpack built 1de34508433fa00a90fc in 654ms

**Comment by ZeroCho** [comment]
this can be easily fixed by adding

mongoose.Promise = global.Promise in server/db/mongo/connect.js

but I don't think we need to make PR because it's up to users to choose which promise library they wanna use.

**Comment by psimyn** [comment]
might be good to settle for one though - currently package.json includes both es6-promise and bluebird

**Comment by ZeroCho** [comment]
@psimyn I don't know bluebird well because I only use es6-promise. Can bluebird be replaced with es6-promise?

**Comment by jrodl3r** [comment]
why not remove bluebird in favor of es6-promise, add `mongoose.Promise = global.Promise;` to connect? One less dep...

**Comment by choonkending** [comment]
Let's try removing bluebird and using es6-promise. I like removing dependencies :)

**Comment by jrodl3r** [comment]
So... instead of removing Bluebird, let's just add this to hide the warning?

```javascript
mongoose.Promise = global.Promise;
```

**Comment by slavab89** [comment]
Fixed in https://github.com/reactGo/reactGo/pull/893
