### ISSUE TITLE
Renaming jsx to js

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#478]
## Enhancement

- Rename all `jsx` files into `js`

**Reason to enhance/problem with existing solution**
- It's really bugging me that we use `jsx`. This is the remnant of the past when we wanted to differentiate between a jsx and js file. Given that this boilerplate is a react app, I don't see value in naming it `jsx` now. 
- Keep kode klean.

**Comment by ZeroCho** [comment]
eslint-plugin-react recommends jsx file extension though...
[Link](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md)

**Comment by caranicas** [comment]
I think I side with @ZeroCho, if a file contains jsx inside it then I think there is some benefit in the file keeping that extension, being explicit about things helps understanding. I don't think there is any real benefit to streamlining the file extensions.

**Comment by jrodl3r** [comment]
Agreed, `.jsx` is a very good visual queue for differentiating between components and other script assets inside the same directory (especially at quick glance in a tree-view). Solid attempt to save a few K tho! ; )

**Comment by choonkending** [comment]
Hahaha alright peeps. I've tried to save us from those few keystrokes.

One last attempt: when we are moving towards the component shuffle (I.e. we
have an index file that exposes the components within the folder), just
hurts my soul when I see jsx and js.

Also we can disable that warning for eslint plugin react.

But this is purely a matter of preference - there are pros and cons either
way. Happy to keep as is. 😉
