### ISSUE TITLE
fetch data logic in route components

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#487]
## Enhancement

**Suggestion by**

@mmollaverdi

**Reason to enhance/problem with existing solution**
- Executing asynchronous API calls in containers never seemed to be the right place, particularly because it's _still_ a view, it should not be it's concern (imo).
- Making a component fetch data through _static_ methods feels hacky. It breaks down when trying to wrap this top level component with page level components, take a look at [this](https://github.com/reactGo/reactGo/compare/get-betta-with-meta#diff-8ac9dc464e1045050db5320e781a72a0R9). Our [prerenderMiddleware](https://github.com/reactGo/reactGo/blob/master/app/middlewares/preRenderMiddleware.js) won't be able to find the `fetchData` method because it is no longer the top level component.
- Because Mehdi "The Don" Mollaverdi said so ;)

**Suggested enhancement**

``` javascript
<Route path="/a" fetch={fetchSpecificRouteData} component={SpecificRouteComponent} />
```

If we have a single `fetchData` method for each route, we no longer need a `Promise.all` in pre-render middleware because we only need to return a single promise.

**Comment by choonkending** [comment]
Couple of other problems exposed when I'm trying to refactor this:
- Having API calls within the actions file makes `actions/topics` have > 1 responsibility. Okay as an initial approach but not ideal. Also couples our fetch API asynchronous calls to redux. Not really necessary tbh.

Trying to make incremental PRs to introduce refactors, but we'll see how this goes :P

**Comment by ramakay** [comment]
👍  On the above thought process on Needs.

**Comment by choonkending** [comment]
Finding a couple more things we should refactor (perhaps later) as I am working on this. Hopefully this makes sense.

In implementing `fetchData`in `Route` components, I have found preRenderMiddleware to be unnecessarily complex.

[**preRenderMiddleware**](https://github.com/reactGo/reactGo/blob/master/app/middlewares/preRenderMiddleware.js)

**Current Behaviour**
- Currently assumes that we have > 1 asynchronous API call per route
- Coupled to redux - it expects a `dispatch` function passed in as an argument
   - Because we dispatch an action object that includes a `promise` attribute, we are also coupling our middleware to the [promiseMiddleware](https://github.com/reactGo/reactGo/blob/master/app/middlewares/promiseMiddleware.js).
```javascript
export function fetchTopics() {
  return {
    type: types.GET_TOPICS,
    promise: makeTopicRequest('get')
  };
}
```

The above is _one_ of the many solutions that work with react-router. However, there is a significant mental overhead when dealing with this middleware. 

Reviewing what we want to achieve with this function. 

**What we essentially need is:**
1. A function that fetches data on route change
2. Once the asynchronous data fetch returns, return that data
3. In our case, we wish to populate our **redux** store with this data

**Suggestions**
1. Simplify `preRenderMiddleware` to just fetch and return the promise.
2. Consumer that calls `preRenderMiddleware` then decides what it wants to do with promise, e.g. `dispatch` to redux store. That greatly simplifies what `preRenderMiddleware`. 
3. For dispatch to be generic, we should be dispatching the same action for all routes. 

A bit tricky, hopefully this makes sense. We'll see how it looks.

**Comment by jrodl3r** [comment]
@choonkending can you explain why we want to fire "CREATE_REQUEST" + "REQUEST_SUCCESS" on every location change? I'm just trying to comprehend the strategy better... As my setup will still have components w/ their own fetching, etc. and the console is a little dirty I guess is my only gripe...

just noticed that is happening on every URL (even w/ { data: undefined }) and not sure if I should be concerned I guess...

**Comment by choonkending** [comment]
Closing in favour of https://github.com/reactGo/reactGo/issues/757#issuecomment-271077728

**Comment by vsc-github** [comment]
@jrodl3r  were you able to find a solution to pass URL params to the fetchData call in the Route component?
