### ISSUE TITLE
sourcemaps, Chrome not loading it

### ISSUE THREAD

**Issue by LarryEitel** [reactGo/reactGo#49]
Running `npm run watchDev` in one tab and `npm run dev` (actually using gulp which reloads server on changes). 

`app.js.map` is being built. However, even though Chrome is configured to handle source maps, I'm not seeing in `Chrome Developer Tools`. Any other hoops I have to jump through? :)

**Comment by choonkending** [comment]
@LarryEitel Thanks for raising this as an issue. I haven't looked into this yet, but will do next week. 

:) Not sure if there are any more hoops to jump through :)

I just pushed a new commit to fix sessions running locally. So `package.json` has changed slightly. You might want to have a look if that affects your workflow.

**Comment by ZeroCho** [comment]
@LarryEitel it looks like webpack's issue. [Link](https://github.com/webpack/webpack/issues/2145)
