### ISSUE TITLE
How to get the domain in server side rendering?

### ISSUE THREAD

**Issue by StefanWerW** [reactGo/reactGo#493]
### Description
- Type: Question

**How to get the domain in server side rendering?**

I'm trying to use the [Youtube Embed Live Chat](https://support.google.com/youtube/answer/2524549?hl=en), and it requires a src in the iframe such _https://www.youtube.com/live_chat?v=12345&embed_domain=**www.example.com**_ where exemple.com is my domain. Since I want it to work in dev mode (localhost) and in the app site, I want to create the src on the fly. When I use:
```
<embed src={`https://www.youtube.com/live_chat?v=${vid}&embed_domain=${location.hostname}`} />
```
it fails silently. Server's up, no error, but no page is served. I assume its because there's no `window` and therefor no `window.location` on the server side rendering.

So how to achieve my goal? How to get the domain in a component, for server and client rendering?

**Comment by caranicas** [comment]
im not sure that localhost will work for that purpose. You will need to expose your local server to the internet. (ngrok)[https://ngrok.com/] can create a tunnel that will should allow you to accomplish what you want.

**Comment by StefanWerW** [comment]
@caranicas I dont think you've understand my question. Let me clarify. Localhost do work, no problem there. What I need is to grab the `window.location.hostname` in a component in the client and *server* side.

Look. If I build with this tag:
```
<embed src={`https://www.youtube.com/live_chat?v=${vid}&embed_domain=${location.hostname}`} />
```
it will build, but the server respond a blank page. On the other hand, if I build without it, and latter add the embed tag, the hot reload will build succesfully but the console throw this:
> warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server

This makes me think that the server side is not accepting `window.location.hostname` or simple `location.hostname`. Since I need the *hostname* in a component, how to get it without the server breaking up silently?

**Comment by ZeroCho** [comment]
I think you'd better add the embed tag after rendering in the client by using componentDidMount method. ComponentDidMount only works in the client and will not make warning.

**Comment by StefanWerW** [comment]
Thanks @ZeroCho !
