### ISSUE TITLE
Loose Dep's

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#504]
Anybody know if there's anything depending on `chai` or `deep-equal`?

I've had both removed from my own build for a while... No issues, and only seeing one instance of either across the entire repo.

Guillotine?

**_Other potentials:_** `immutable`, `invariant`, `kerberos`, `node-libs-browser`

**_Note:_** duplicate dev-dependency `redux-mock-store` in dependencies.

Sorry if any of these are obvious necessities, my build is pretty light.

**Comment by choonkending** [comment]
Kill it!!

**Comment by choonkending** [comment]
Hehe nice work

**Comment by caranicas** [comment]
anything to reduce the number of greenkeeper PRs

**Comment by choonkending** [comment]
Yes. Agreed. Kill them with 🔥 

If you get to test them and have no issues, just merge them!

**Comment by jrodl3r** [comment]
@caranicas greenkeeper seems like overkill, it clogs-up the commit log

**Comment by ZeroCho** [comment]
I agree with @jrodl3r `npm update -S` is enough
