### ISSUE TITLE
How to replace postCSS with SCSS?

### ISSUE THREAD

**Issue by iKonrad** [reactGo/reactGo#513]
## Question

**How to?**
First of all - thanks for the great boilerplate. It's superb although I'm not sure if I want to learn PostCSS at the moment (ReactJS is enough).
I'm working towards removing PostCSS and all its signs from the boilerplate. I've no issues with installing the sass-loader and node-sass, it's just I want to make sure that there's nothing left for the PostCSS. Could you point me into the right direction?

Thanks!!

**Comment by caranicas** [comment]
there is an answer given in #332 

@choonkending want to add an that as an explanation to the read me, because I feel like this question is going to keep popping up.

Alternatively as we move to 2.0 is style implementation something we want to break out into its own project, or do you think that complicates things too much?

**Comment by choonkending** [comment]
Thanks @iKonrad!

> It's superb although I'm not sure if I want to learn PostCSS at the moment (ReactJS is enough).

I can understand that concern.

To only use `sass-loader` without postcss plugins, you would look at replacing [this](https://github.com/reactGo/reactGo/blob/master/webpack/webpack.config.dev-client.js#L87...L90) and [this](https://github.com/reactGo/reactGo/blob/master/webpack/webpack.config.dev-server.js#L53...L56) bit for dev mode and [this](https://github.com/reactGo/reactGo/blob/master/webpack/webpack.config.prod.js#L40-L42) bit in production mode with something such as below:

```scss
{
     test: /\.scss$/,
    loader: ExtractTextPlugin.extract('style-loader', 'scss-loader')
}

```

Hahaha. @caranicas you're too quick! Yes, we definitely need to write up a README for this.

**Comment by iKonrad** [comment]
Thanks guys for immediate answer!
I've put that line in place and now it's complaining that the ExtractTextPlugin doesn't exist. Have I missed something?

**Comment by caranicas** [comment]
@iKonrad `var ExtractTextPlugin = require('extract-text-webpack-plugin');` is currently only found in `webpack.config.prod.js ` you probably just need to add it to the `webpack.config.dev-client.js`

**Comment by caranicas** [comment]
so one my my production projects is using an older version of this boilerplate, when we were still using scss. 


in webpack.dev i have the following

```
module: {
      loaders: commonLoaders.concat([
        { test: /\.scss$/,
          loader: 'style!css?module&localIdentName=[local]' + //__[hash:base64:5]
            '&sourceMap!postcss-loader!sass?sourceMap&outputStyle=expanded' +
            '&includePaths[]=' + encodeURIComponent(path.resolve(__dirname, '..', 'app', 'scss'))
        }
      ])
    },
```

and in webpack.dev.server i have

```
module: {
      loaders: commonLoaders.concat([
           { test: /\.scss$/,                                                                           //__[hash:base64:5]
             loader: ExtractTextPlugin.extract('style-loader', 'css-loader?module&localIdentName=[local]!postcss-loader!sass?includePaths[]='
                                               + encodeURIComponent(path.resolve(__dirname, '..', 'app', 'scss')))
           }
      ])
    },
```

I moved the `__[hash:base64:5]`  because I couldn't get it to jive with some external libs. 
but if you look at how it is being used with postCSS then you can put it back if you'd like.

```
loader: 'style!css?module&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader'
```

**Comment by iKonrad** [comment]
Sorry to be a pain, but now I'm getting:
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

Have you declared any plugins with it?

**Comment by iKonrad** [comment]
Right, I've added the plugins for scss files and then
`require('style!css!sass!styles/app.scss');`
in App.jsx but now I'm getting:

> Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"

It looks like my stylesheet goes through the parser twice. How should I import my SCSS stylesheet into the app?

**Comment by iKonrad** [comment]
Removing style!css!sass from the require does the trick. :)
Thanks a lot!

**Comment by caranicas** [comment]
yeah, glad to help. Feel free to any more questions you may have. If you could write up some a docs outlining your process for moving down to scss that would really be awesome. 💯   Put it in the docs folder and then link it too it from  the [css page](https://github.com/reactGo/reactGo/blob/master/docs/css.md)

**Comment by donpinkus** [comment]
Just spent about 6 hours trying to get it converted but no success :(

Adding it to the docs would be super appreciated @iKonrad / @caranicas!

**Comment by donpinkus** [comment]
By using this repo - https://github.com/donpinkus/reactgo-scss

**Comment by vsc-github** [comment]
@choonkending thanks for providing a solution, but the solution you've provided is not applicable anymore. Could you throw some light on how can I integrate SASS/SCSS with the current state of the boilerplate.

Any, help is much appreciated.
