### ISSUE TITLE
React Awesome out of date

### ISSUE THREAD

**Issue by StefanWerW** [reactGo/reactGo#521]
### Description
- Enhancement
- Related Issue: https://github.com/enaqx/awesome-react/pull/522/files

---
## Enhancement

**Reason to enhance/problem with existing solution**
The description and repo link in [React Awesome](https://github.com/enaqx/awesome-react) are out of date

**Suggested enhancement**
The owners of reactGo create a PR to update it.

I've created a [PR](https://github.com/enaqx/awesome-react/pull/522/files) but I dont know if they will accept one time I'm not a reactGo owner.

**Pros**
Self explanatory

**Cons**
No cons

**Comment by choonkending** [comment]
Thanks mate! 👍
