### ISSUE TITLE
Babel --ignore problem 

### ISSUE THREAD

**Issue by shakaIsReal** [reactGo/reactGo#535]
In `package.json`  I had `--ignore node_modules,public`. This will ignore filenames like `getPublicKey.js`. Please change this to`--ignore node_modules,public/*` so it's invoked for folders only :) 

Thanks, great work

**Comment by slavab89** [comment]
We're cleaning the project of stale issues therefore i'm closing this. The codebase has changed quite a bit since the issue was opened.
If you still have any issue, please comment here or open a new issue.
