### ISSUE TITLE
Async OnEnter causing React error

### ISSUE THREAD

**Issue by StefanWerW** [reactGo/reactGo#537]
### Description
- Type: Bug

---
## Bug

Using a async function on React router onEnter hook is causing react to print a error.

Code on `app/routes`:

``` jsx
  const asyncOnEnter = (nextState, replace, callback) => {
    setTimeout(callback, 3000);
  };
  return (
    <Route path="/" component={App}>
      <IndexRoute component={Vote} fetchData={fetchVoteData} />
      <Route path="login" component={LoginOrRegister} onEnter={redirectAuth} />
      <Route path="dashboard" component={Dashboard} onEnter={requireAuth} />
      <Route path="about" component={About} onEnter={asyncOnEnter} />
    </Route>
  );
```

**Expected Behavior**
No errors

**Actual Behavior**
On browser console:

> warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) <!-- react-empty: 1 -
>  (server) <div class="main__appprintWarning @ warning.js:36warning @ warning.js:60_mountImageIntoNode @ ReactMount.js:508mountComponentIntoNode @ ReactMount.js:113perform @ Transaction.js:138batchedMountComponentIntoNode @ ReactMount.js:127perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98_renderNewRootComponent @ ReactMount.js:321_renderSubtreeIntoContainer @ ReactMount.js:402render @ ReactMount.js:423(anonymous function) @ client.jsx:66(anonymous function) @ app.js:592__webpack_require__ @ app.js:556fn @ app.js:87(anonymous function) @ multi_app:1(anonymous function) @ app.js:586__webpack_require__ @ app.js:556(anonymous function) @ app.js:579(anonymous function) @ app.js:582

**Steps to Reproduce**

Create any async function on `onEnter` hook 

---

**Comment by StefanWerW** [comment]
Maybe something here: ReactTraining/react-router#2714

**Comment by slavab89** [comment]
We're cleaning the project of stale issues therefore i'm closing this. The codebase was changed quite a bit since this issue was opened. Moreover, the specific error that you see is related to the server render vs client render that are not the same. 
If you still have any issue, please comment here or open a new issue.
