### ISSUE TITLE
eslint/lint doesn't check files in new directories under app

### ISSUE THREAD

**Issue by DraconPern** [reactGo/reactGo#539]
### Description
- Type: Question

## Question
using npm run lint on a project with new files under app/newdir, lint doesn't seem to check new files.

**Comment by ZeroCho** [comment]
Hmm... that's strange. Please show me .eslintignore

**Comment by DraconPern** [comment]
here's what I have

/compiled/**
/public/**
/webpack/**
karma.conf.js
tests.webpack.js
/api/promiseMiddleware.js

**Comment by DraconPern** [comment]
Ah.. it doesn't read jsx files.

**Comment by GGAlanSmithee** [comment]
@DraconPern see #569
