### ISSUE TITLE
Change the name of google app

### ISSUE THREAD

**Issue by ZeroCho** [reactGo/reactGo#540]
Note: This is just a template, so feel free to use/remove the unnecessary things
### Description
- Type: Enhancement
## Enhancement

**Reason to enhance/problem with existing solution**
Currently, when logging in with google accounts, google says "Login to React Webpack Node"

**Suggested enhancement**
Need to change the google app name to ReactGo

**Comment by StefanWerW** [comment]
If the dev go to this trouble I would also recommend change the Heroku app. 

### Demo site:

https://react-webpack-node.herokuapp.com/

### Maybe better:

https://reactgo.herokuapp.com/
