### ISSUE TITLE
unauthenticated user gets authenticated

### ISSUE THREAD

**Issue by GGAlanSmithee** [reactGo/reactGo#546]
## Bug

**Expected Behavior**
User must provide correct email and password to be authenticated (logged in)

**Actual Behavior**
User gets authenticated (logged in) when providing the wrong password

**Steps to Reproduce**
- set up project
  - `git clone git@github.com:reactGo/reactGo.git`
  - `npm i`
- set up postgresql according to [the guide](https://github.com/reactGo/reactGo/blob/master/docs/databases.md#databases)
  - _note: I had to set the password for the root user to '' (empty string) since null didn't work_
- Start application
  - `npm run build && npm run start`
- create a new user
  - email **user@email.com**
  - password **pass**
- logout
- Attempt to login again, using bad info
  - email **user@email.com**
  - password **badpass**

**Additional info**

```
$ node -v
>v6.6.0
$ npm -v
> 3.10.3
$ psql
> psql (9.3.14)
```

From some quick debugging I could trace the problem to line 72 in `server/db/sequalize/models/users.js`, where `bcrypt.compareAsync(candidatePassword, this.password)` wrongfully authenticates the user. Seems unlikely though, so probably a red herring

**Comment by shredd** [comment]
Found the issue in <code>server/db/sequalize/passport/local.js</code>
In the comparePassword callback:
<code>(result) => {
        if(result) done(null, user);
        else done(null, false, { message: 'Your email/password combination is incorrect.' });
      }
</code>

**Comment by GGAlanSmithee** [comment]
Closed in #648 thanks @shredd 🎉
