### ISSUE TITLE
Add a 404 custom page.

### ISSUE THREAD

**Issue by StefanWerW** [reactGo/reactGo#572]
### Description
- Enhancement

---
## Enhancement

**Reason to enhance/problem with existing solution**
When a user enters a not valid URL, it would be nice to be redirected to a 404 page, or the index page.

**Suggested enhancement**
Custon 404 page

**Pros**
Cleaner website

**Cons**
Don't know

---

**Comment by ZeroCho** [comment]
```
<Route path="/" component={App}>
      <IndexRoute component={Vote} fetchData={fetchVoteData} />
      <Route path="login" component={LoginOrRegister} onEnter={redirectAuth} />
      <Route path="dashboard" component={Dashboard} onEnter={requireAuth} />
      <Route path="about" component={About} />
      <Route path="*" component={NotFound} status={404} />
    </Route>
```
will work. Need to make NotFound component.

**Comment by GGAlanSmithee** [comment]
@ZeroCho nice suggestion. I am handling it here https://github.com/reactGo/reactGo/blob/master/app/server.jsx#L129 but I like your idea more.
