### ISSUE TITLE
Heroku ssl redirect

### ISSUE THREAD

**Issue by StefanWerW** [reactGo/reactGo#598]
### Description
- Type: Enhancement

When a user access the website without the `https` protocol prefix on the url, many problems may occur.
Errors:
- If the dev does not set a `GOOGLE_CALLBACK` with full path, or he uses the [relative path from secrets.js](https://github.com/reactGo/reactGo/blob/affa81c7ef429c133ba5c866aeef9471a85eaedc/server/config/secrets.js#L8), Google login will fail silently(sometimes with error depending on your credentials config).
- If a user have already logged in, but came back without the `https` prefix url, the session will be log out.
- Many other secure issues

The reason is because we have [cookies set to secure](https://github.com/reactGo/reactGo/blob/affa81c7ef429c133ba5c866aeef9471a85eaedc/server/config/express.js#L88), so http will no do it.

When it can occur:
- Users accessing a link without `https://` prefix on it.
- Users typing the website address (who does type `https://` anyways?)
## Enhancement

**Suggested enhancement**

Redirect the user to a https connection on the production environment.

We could have something like this (extracted from [here](https://github.com/nodenica/node-heroku-ssl-redirect)):

``` js
function sslRedirect(environments, status) {
  environments = environments || ['production'];
  status = status || 302;
  return function(req, res, next) {
    if (_.contains(environments, process.env.NODE_ENV)) {
      if (req.headers['x-forwarded-proto'] != 'https') {
        res.redirect(status, 'https://' + req.hostname + req.originalUrl);
      }
      else {
        next();
      }
    }
    else {
      next();
    }
  };
};

app.use(sslRedirect());
```

**Pros**
Fix some issues.

**Cons**
Production in other production environments than Heroku may not work due to `req.headers['x-forwarded-proto']`.

**Extra Reading**
http://jaketrent.com/post/https-redirect-node-heroku/

**Comment by ZeroCho** [comment]
I'm using that codes in my heroku blog and it works like charm. But, i'm not sure it will work on other environments

**Comment by jrodl3r** [comment]
Hey guys, I ran into this issue as well just now (SSL not working unless you explicitly go to "https://..." on Heroku) and I was wondering if either of you have a more up-to-date solution?

Is this something that can be handled by say DNSimple, or somewhere else in the pipeline?

Thx! @psimyn @choonkending

**Comment by choonkending** [comment]
I think that's a good first step @jrodl3r !!

**Comment by choonkending** [comment]
Thinking about this a bit further. It _does_ feel like NGINX (or similar) would be a better fit for this problem. I do not want to bloat this repo with more config. Maybe we can implement your solution but also document it with a recommendation for a proxy server that handles redirects. 🤔

**Comment by jrodl3r** [comment]
your call. we can always just leave it here... I would hesitate to even add it commented out with inline notes because of the additional config it adds. Either way, problem solved ; )
