### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by jkomyno** [reactGo/reactGo#600]
Note: This is just a template, so feel free to use/remove the unnecessary things
### Description
- Type: Bug
## Bug

With both DB_TYPE=MONGO or DB_TYPE=NONE it crashes on startup. I'm on Windows.

npm@3.9.3
node@5.1.1

Log:

c:\lavoro\reactGo>npm run dev

> react-webpack-node@1.7.17 dev c:\lavoro\reactGo
> cross-env NODE_ENV=development nodemon

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app/server.jsx app/routes.jsx app/helmconfig.js app/componen
ts/Meta.jsx c:\lavoro\reactGo\server/*_/_ webpack/webpack.config.dev-client.js w
ebpack/webpack.config.dev-server.js .stylelintrc
[nodemon] starting `npm run build:dev && npm run babel-node -- server/index.js`

> react-webpack-node@1.7.17 build:dev c:\lavoro\reactGo
> cross-env NODE_ENV=development webpack --colors --config ./webpack/webpack.con
> fig.dev-server.js

Hash: 3b222b83920f56a813ff
Version: webpack 1.13.2
Time: 5823ms
    Asset     Size  Chunks             Chunk Names
server.js  1.24 MB       0  [emitted]  server
    + 366 hidden modules

> react-webpack-node@1.7.17 babel-node c:\lavoro\reactGo
> babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index
> .js"

Attempted to use '(de)serialize User' but DB type 'NONE' doesn't support it
Attempted to use 'passport-local' but DB type 'NONE' doesn't support it
Attempted to use 'passport-google-oauth' but DB type 'NONE' doesn't support it
## Attempted to use 'session' but DB type 'NONE' doesn't support it

===> ?  Starting Server . . .
===>  Environment: development
===>  Listening on port: 3000
## ===>  Using DB TYPE: NONE

Attempted to use 'users routes' but DB type 'NONE' doesn't support it
Attempted to use 'topics routes' but DB type 'NONE' doesn't support it

webpack building...
webpack built 469c4d226cd6f046d599 in 22305ms
{ [Error: Request failed with status code 404]
  config:
   { transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     headers:
      { Accept: 'application/json, text/plain, _/_',
        'User-Agent': 'axios/0.14.0' },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     baseURL: 'http://localhost:3000',
     method: 'get',
     url: 'http://localhost:3000/topic',
     data: undefined },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { 'x-powered-by': 'Express',
        'content-type': 'text/plain; charset=utf-8',
        'content-length': '9',
        etag: 'W/"9-nR6tc+Z4+i9RpwqTOwvwFw"',
        date: 'Tue, 11 Oct 2016 07:24:51 GMT',
        connection: 'close' },
     config:
      { transformRequest: [Object],
        transformResponse: [Object],
        headers: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        baseURL: 'http://localhost:3000',
        method: 'get',
        url: 'http://localhost:3000/topic',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /topic HTTP/1.1\r\nAccept: application/json, text/plain, *
/*\r\nUser-Agent: axios/0.14.0\r\nHost: localhost:3000\r\nConnection: close\r\n\
r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/topic',
        parser: null,
        res: [Object] },
     data: 'Not Found' } }

Any idea on how to address this issue?

**Comment by ZeroCho** [comment]
AFAIK, DB_TYPE NONE has a problem currently. We need a fix.

**Comment by jkomyno** [comment]
Actually it gives me problems even with mongod running and with
DB_TYPE=MONGO

Il 11/ott/2016 09:33, "Hyunyoung Cho" <notifications@github.com> ha scritto:

**Comment by RyleeHarrison** [comment]
Windows' doesn't work on Windows
