### ISSUE TITLE
Dockerizing the project

### ISSUE THREAD

**Issue by slavab89** [reactGo/reactGo#631]
Note: This is just a template, so feel free to use/remove the unnecessary things
## Enhancement

**Reason to enhance/problem with existing solution**
So we like out boilerplate and we're working with it :) and there is the trend of dockerizing everything :)
What do you think about doing the same for this boilerplate?
I have started working on this on my project and can share what i did so far but i do have some issue that i'm struggling with and could use some help and opinions about how to do it

**Suggested enhancement**
Add docker files to this boilerplate (for dev and production)

**Pros**
Working in docker containers during development brings us closer to working on the real environment that we will finally run on (probably some linux)

**Cons**
Because the app will be running inside a container instead of the native OS, webpack builds and module changes will take a little longer to happen

Let me know if its relevant or redundant to this boilerplate

**Comment by brtw** [comment]
I've got a production solution for this. I develop on my native os and do staging and production in docker. Not sure how much value developing in docker would provide. If you would like I can share my solution for you.

**Comment by slavab89** [comment]
@brtw If you could share your solution it would be great.
I'll then open a PR with the combined ideas for anyone that might be interested

**Comment by brtw** [comment]
@slavab89 My strategy is to clone my production branch from the project's git repo, build and and run. I created a new ssh key specifically for cloning. I had various versions; some with the host os already updated and upgraded, others doing git pulls, but the following is the all-in-one solution.

My file structure is as follows:
```
/NodeDocker/
/NodeDocker/Dockerfile
/NodeDocker/ssh/
/NodeDocker/ssh/config
/NodeDocker/ssh/id_rsa
/NodeDocker/ssh/id_rsa.pub
```

config file:
```
# ssh/config
# Git keys
host gitlab.com
     user git
     port 22
     identityfile /root/.ssh/id_rsa
```

Dockerfile:
```
############################################################
# Dockerfile to build React Webapp container images
# Based on Node
############################################################

FROM node:5.11

# File Author / Maintainer
MAINTAINER brtw

# Update the repository sources list
RUN apt-get update

################## BEGIN INSTALLATION ######################

# Install git and ssh 
RUN apt-get update && apt-get install -y ca-certificates git-core ssh

# add custom ssh config / keys to the root user
ADD ssh/ /root/.ssh/

# Fixes permission if needed
RUN chmod 600 /root/.ssh/*

# Avoid first connection host confirmation
RUN ssh-keyscan -p22 gitlab.com > /root/.ssh/known_hosts

# Create app directory
RUN mkdir -p /usr/src
WORKDIR /usr/src

# Clone Boilerplate
RUN git clone gitlab.com:gituser/gitrepo.git
WORKDIR /usr/src/gitrepo

# Manage NPM Priority
RUN npm config set jobs 1

# Install npm dependencies
RUN npm install

EXPOSE 3000

# Build and run application
RUN npm run build

# Run prod
CMD ["npm", "start"]
```

And that's it. Let me know if that helps and if you have any questions or suggestions!

**Comment by Cleanshooter** [comment]
I've been using docker for mine for quite a while now.  I don't worry too much about personal ssh keys since my auth keys to my docker repo encapsulate traffic between me and my prod/test containers when I bin/bash into them.  I haven't quite figured out HTTPS yet though... (always something to add to the todo list)

I use a separate mongo container and link it when I run my container, its best to separate for data persistence during development.

Docker file:
```
FROM node:boron

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app and dependencies
COPY package.json /usr/src/app/
RUN npm install

# Copy build
COPY compiled /usr/src/app/compiled
COPY public /usr/src/app/public

# Set Environment Variables
ENV MONGODB_URI mongodb://mongo/my-app
ENV NODE_ENV production
ENV PORT 80

EXPOSE 80

CMD ["node", "compiled/server.js"]
```

Local build (testing) process commands:
(Build)
1. `npm run build`
2. `docker build -t my-app .`
(Restart my local mongo DB)
3. `docker restart my-app-linked-db`
4. `docker run -d -p 127.0.0.1:80:80 -it --link my-app-linked-db:mongo --name my-app-test my-app`

Right now I'm working on a GitLab pipeline to automate this process so when I do a `git push origin` the linter runs, then the unit tests and if all those are good it builds, pushes and deploys to my docker repo and starts the container in my TEST environment.  But it's still a work in progress.

**Comment by slavab89** [comment]
😱 i totally forgot that i opened this issue.
thanks for the reminder!
I'm using a similar build to @Cleanshooter that utilizes caching the container of installed npm modules.
On my end i've also added a specific user for the container itself. This is so that the application wont run on `root` user inside the container. Even though its a container and not the actual host machine, i've read that its not the best option to run stuff on root.

I'm using docker-compose to run the containers and use `Dockerfile` only to build the image itself.

Regarding HTTPS, i actually didnt add this logic into docker yet and i'm thinking about the following
Have an additional container that will only have the certificates. That container will be linked to the application container. There should also be a script that runs once the certificates are updated and restarts the application container and links the latest container of the certificates.

Last thing.. I think its preferable not to bind the application to port 80. The docker container should run in some port (ex. 3000) and have some kind of load balancer / nginx that does port forwarding. We've talked about this briefly on https://github.com/reactGo/reactGo/issues/245

**Comment by Cleanshooter** [comment]
Having a container just for the certs... f'ing brilliant.  I LOVE it.  Totally adding this to my build.  

@slavab89, it make a lot of sense to stack the nginx server in front of that... it'll make scaling up your app with new containers easier going forward.  

Could you post your docker-compose file and docker file, the one that builds the user?  I'd love to see it/steal it 😄 .

**Comment by slavab89** [comment]
Sure thing!
This is mostly based on the following resources:
https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md
https://nodesource.com/blog/8-protips-to-start-killing-it-when-dockerizing-node-js/

I've noticed a couple of days ago that my development build doesnt work on Linux. It has something to do with the additional user that i've created. Based on the latest article it might be related to to `Protip 2` which i didnt do. Also, there should be a `node` user when using node base images so maybe it will work without creating a new user.

I didnt change the dockerfile in quite some time so i need to revisit that 😄  (docker-compose version 3, the user thing, dont really like the chown that i do hehe)

Dockerfile
```
FROM node:6.10.1
# This might need to change
RUN useradd --user-group --create-home --shell /bin/false nodejs
RUN npm install -g pm2

ENV HOME=/home/nodejs

COPY package.json $HOME/app/package.json
RUN chown -R nodejs:nodejs $HOME/app

USER nodejs
RUN cd $HOME/app && npm install --production

WORKDIR $HOME/app
USER root
COPY . $HOME/app
# Change owner of files except node_modules to the user
RUN find $HOME/app -name "node_modules" -prune -o -print0 | xargs -0 chown nodejs:nodejs

USER nodejs
RUN npm run build

EXPOSE 3000
```

docker-compose.yml
```

version: '2'

services:
  main-ui:
    container_name: main-ui
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules
    command: npm run dev
```

docker-compose.production.yml
```

version: '2'

services:
  main-ui:
    container_name: main-ui
    image: main-ui:latest
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - /var/log/main-ui/:/home/nodejs/app/logs/
    command: pm2 start compiled/server.js --no-daemon
```

**Comment by slavab89** [comment]
So after playing around a little more, this is the final dockerfile that i'm currently using. I think it works better and builds a bit faster. Moreover, i'm using the capabilities that the node base image contains

```yaml

FROM node:boron

# Add Tini (For isolated run)
ENV TINI_VERSION v0.15.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /home/node/tini
RUN chmod +x /home/node/tini
ENTRYPOINT ["/home/node/tini", "--"]

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY package.json /home/node/app
RUN npm install && npm cache clean

COPY . /home/node/app
RUN npm run build

EXPOSE 3002
USER node

CMD ["node", "compiled/server.js"]
```

Please note that the whole `/home/node/app` folder will be under `root` privileges, while the application itself runs under `node` user. This means that any interaction with the disk or whatever cannot be performed. In case you need it, change the contents on the folder to belong to use `node` or pre-create folders / files for that user.

Moreover, the modules installation and webpack building is done inside the container so that everything will be system specific (In case we have modules that are compiled)
