### ISSUE TITLE
How to @import url(...)?

### ISSUE THREAD

**Issue by oleole90** [reactGo/reactGo#652]
### Description
- Type: Question
The screenshot of the project below is building correctly in dev and prod.
I'm just trying to put my component and its style together in one folder. Importing with reative path works but **@import '../../css/common/typography';** is an eyesore, IMO.
Can I import using **@import url('...');**?

-----------------------------------------------------------------

## Question

**How to @import url(...)?**

![image](https://cloud.githubusercontent.com/assets/4123376/19925609/e341cd46-a11a-11e6-94c2-20ec99ac84b8.png)

**Comment by psimyn** [comment]
does this work?

```
 @import 'css/common/typography';
```

**Comment by oleole90** [comment]
Nope..

**Comment by oleole90** [comment]
wait... who cares! Moving on.
