### ISSUE TITLE
How to implement SMS verification in reactGo?

### ISSUE THREAD

**Issue by minvedacat** [reactGo/reactGo#682]
Mobile web apps or sites now require you to verify your mobile phone number by sending a 6 or 4 code to you before you register new account. After successful registration, the verified number is automatically linked with your account.
Apparently, the server should keep the secret code, page refresh and timeout staff should fail the process and you have to request for a new SMS code. 

Is there any good practice in reactGo to implement such feature?

**Comment by slavab89** [comment]
We're cleaning the project and closing issues.
This issue is not really related to reactGo project but you can try and check services such as Auth0 and similar which i believe have this logic and you can add it to your project.
