### ISSUE TITLE
Map errors in compiled file to actual file

### ISSUE THREAD

**Issue by donpinkus** [reactGo/reactGo#685]
## Question

When I get an error that only appears in production, it's hard to debug since I just get a line & char number in the compiled server.js file.  How can I map this to the the actual file & error? 

Is the best solution just to look at the code in the compiled server.js file and try to tell where the error is coming from, or is there a more precise way?

**Comment by slavab89** [comment]
I also encountered something similar where i had a bug in production happening and it was a nightmare to try and find the code - bottom line, it was pretty impossible as the code is uglified and minified etc..
I think the best way is to try and reproduce it in dev. The code is deterministic so there is no reason that something will happen in prod but not in dev.

**Comment by donpinkus** [comment]
There is one very common reason for bugs that are ONLY in prod: in prod the pages are loaded server side.

**Comment by slavab89** [comment]
In dev they are loaded on the server side as well...
When you first access some page then it does the server loading (running the code the server.jsx).

**Comment by slavab89** [comment]
We're cleaning up the project and trying to close issues.
If you still have an issue, please comment here or open a new one.
