### ISSUE TITLE
Error with postcss import

### ISSUE THREAD

**Issue by FrenchBully** [reactGo/reactGo#687]
Hello, just wondering if anyone has run into any issues with not being able to import css files?  All I get are undefined variables.

breakpoints.css
```
:root {
  --breakpointPhoneSmall:     320px;
  --breakpointPhoneMedium:    375px;
  --breakpointPhoneLarge:     512px;
  --breakpointPhoneXLarge:    640px;
  --breakpointTablet:         768px;
  --breakpointDesktopSmall:   1024px;
  --breakpointDesktopMedium:  1280px;
  --breakpointDesktopLarge:   1440px;
  --breakpointDesktopXLarge:  1920px;

  @custom-media --tablet (min-width: 768px);
  @custom-media --desktop (min-width: 1024px);
}
```

main.css
```
@import './breakpoints';

.photoAnalyzer {
  display: flex;
  flex-direction: column;

  @media (--desktop) {
    box-shadow: 0px 2px 16px 0px rgba(0,0,0,0.20);
    position: relative;
    height: calc(100vh - 125px);
    flex-direction: row;
  }
}
```

**Comment by ZeroCho** [comment]
your css file name is **breakpoint** and import name is **breakpoints** not plural right?

**Comment by FrenchBully** [comment]
oh sorry that was a typo in the question.

**Comment by FrenchBully** [comment]
Found the issue, looks like postcss-import up their version and it's breaking the build.  Change "postcss-import": "^8.0.2" to "postcss-import": "8.0.2" so it to doesn't pull the latest version and you should be fine.
