### ISSUE TITLE
Catching Fetch Error in an Event Handler

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#692]
when performing a fetch() in an onClick handler...
```javascript
const handleTeamClick = (e) => {
  e.preventDefault();
  fetchTeam(team.id)
    .then(() => { updateUI(); })
    .catch(err) => { ...this-would-be-awesome... });
```
can't seem to figure out an approach to catch a response error... and avoiding `updateUI()`

**Comment by choonkending** [comment]
hmm. It would really depend on how the error is thrown. 

If I understand the problem correctly, I would do something like below
```js
fetchTeam(team.id)
   .then(response => {
        if (response.status === 200) updateUI(..something);
        else throw new Error("some message"); 
   })
   .catch(err => doSomething());

```

Hopefully that helps!

**Comment by jrodl3r** [comment]
@choonkending response is undefined when I try to .then() it...

here is what the action looks like:
```javascript
export function fetchTeam(id) {
  return {
    type: types.GET_LEAGUE_TEAM,
    promise: request.get('/league/' + id)
  };
}
```

**Comment by choonkending** [comment]
That looks good to me @jrodl3r  !

This is why I am backtracking on promise middleware. I find that it's not a core requirement in our hat's actually why I don't actually like coupling request fetching/promises with `redux`.

Although it does make request handling a lot easier, I find that having a promise middleware has a bit of an overhead:
- tightly couples request fetching to redux
- in making promise `SUCCESS` and `FAILURE` generic, we make it hard to handle specific cases, or handle network exceptions.

Redux is an awesome way to handle state easily. I do not think that promise handling/request fetching is a `redux` concern though.

For example,

```js
const fetchTeam = id => {
   return service.makeCall(id)
       .then(data => { // do something without promise middleware or redux }
       .catch(err => { });
}

// Then using a Component that connects to redux, we can use a dispatch to 

this.props.dispatch(fetchTeam(id)); // Hopefully this works
```

(I'm also trying to get buy-in to remove promise middleware haha)

**Comment by jrodl3r** [comment]
I like it! You'll have my vote 👍  ...and I know the current setup is not _perfect_, but it's pretty solid. My projects are pretty simple, so I'm not too picky.

**Comment by slavab89** [comment]
We're cleaning up the project and trying to close issues. The code base has changed since this issue was opened and it seems to have been resolved (?)
If you still have an issue, please comment here or open a new one.
