### ISSUE TITLE
Cull the unneeded dependencies!

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#705]
## Enhancement

**Reason to enhance/problem with existing solution**
- The less we support, the simpler this project will become! And the easier it is to optimize and improve on performance and code quality!
- Improves delivery effectiveness! 🚢 

**Suggested enhancement**
- Remove unneeded babel plugins
    - [ ] https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy
    - [ ] https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements
    - [ ] https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types
- [x] isomorphic-fetch (we already use axios)

I'm referencing create react app's babel plugins as well, over [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/package.json)

Please suggest more if you find an unneeded dependency!

**Comment by jrodl3r** [comment]
just leaving "babel-plugin-transform-react-inline-elements"?

**Comment by choonkending** [comment]
You mean remove it?  🎉

**Comment by jrodl3r** [comment]
no. I was just asking..

**Comment by choonkending** [comment]
I might have to double check. It promises to make production code faster but I haven't seen many projects using it.

**Comment by slavab89** [comment]
Some of the dependencies were already removed (linked PR's) so i suggest we close it. We can always try and clean up additional dependencies and open more issues.
