### ISSUE TITLE
Problem when implementing async routing

### ISSUE THREAD

**Issue by ZeroCho** [reactGo/reactGo#709]
### Description
- Type: Bug

---------------------------------------------------------------
## Bug
**Expected Behavior**
When implementing async routing, each route should be bundled separately, so that each page can be loaded separately when I visit that page.

**Actual Behavior**
Whole pages are served at once. So initial loading is very slow. I found out that this problem is due to `pages/App`. We don't need this because we already have `containers/App`, and each pages can still access `Helmet` without `pages/App`.
Actually, App is not a stand-alone page but a container
I'm preparing PR for this.

**Steps to Reproduce**
It happens when implementing async routing, so there's no possible way to reproduce my problem.

**Comment by choonkending** [comment]
Thanks for raising this! The entire page is served at once?

I actually implemented the meta changes without a `pages/App` initially, and introduced it later on in https://github.com/reactGo/reactGo/pull/675/commits/d3f7e61ab9b0e25bbf8a59683f11c05840979786 for page level common config.

E.g.

`<meta>` tags that were shared across different pages. So then the nested routes would then not need to require and override/resolve all the additional tags. 

More of the thought process was documented https://github.com/reactGo/reactGo/pull/675#issuecomment-260159972 (it's quite long, sorry!)

I am not quite sure how to solve this yet at the moment though :(

**Comment by choonkending** [comment]
Is it because the client side router becomes slower with the `pages/App` having to deal with app specific meta tags as well?

**Comment by ZeroCho** [comment]
I personally removed `pages/App` in my project. Because all pages share `pages/App`, webpack doesn't recognize each page as separate one, so it bundles everything in one js file, although I used `require.ensure` to bundle it separately.
After I removed `pages/App`, webpack began to recognize pages as separate ones.
For page level common config, I'm now using concat to server metas and links because there is no `pages/App`
```
import { link as linkAssets } from 'config/headAssets';
...
pageLink = () => (linkAssets.concat([
    { rel: 'stylesheet', href: '//cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/themes/prism-okaidia.min.css' },
    { rel: 'stylesheet', href: '//cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/plugins/line-numbers/prism-line-numbers.min.css' },
  ]));
```

**Comment by choonkending** [comment]
Ah I see! I personally haven't played around with separate bundling so far, really have to look into that.

**Comment by choonkending** [comment]
Interesting. 

I didn't know that `require.ensure` helped with code splitting! Alright. I wonder why setting a root container with `containers/App` still works (with require.ensure) and `pages/App` does not work. 

One work around this would be to pass all the config to every page as you suggested and let react-helmet work it out.

I'd like to do a bit of thinking around this. Would you mind showing your code for the concatenating as a branch or WIP PR just so we can take it from there?

**Comment by ZeroCho** [comment]
@choonkending #710
