### ISSUE TITLE
throw new mongoose.Error.OverwriteModelError(name);

### ISSUE THREAD

**Issue by hhelb** [reactGo/reactGo#720]
### Description
- Type: Question

Hello guys!
Thank you for this awesome repo. I am currently learning react and this stack is awesome.
I am using mongoDB and I am trying to add a new table to the database. 
I followed the code for "Topics" in order to create my own table but I get this error : 
**throw new mongoose.Error.OverwriteModelError(name);**

### models/fiches.js:
```
import mongoose from 'mongoose';

const FicheSchema = new mongoose.Schema({
    id: String,
    text: String
});
export default mongoose.model('Fiche', FicheSchema);
```
### controllers/fiches.js:

```
import Fiche from '../models/fiches';

export function all(req, res) {
    Fiche.find({}).exec((err, fiches) => {
        if (err) {
            console.log('Error in first query');
            return res.status(500).send('Something went wrong getting the data');
        }

        return res.json(fiches);
    });
}

export default{
    all
};
```
### controllers/index.js :
```
import topics from './topics';
import users from './users';
import fiches from './fiches';

export { topics, users, fiches  };

export default {
  topics,
  users,
  fiches
};
```
### finally the routes:
```
[...]
import { controllers, passport as passportConfig } from '../db';
const usersController = controllers && controllers.users;
const topicsController = controllers && controllers.topics;
const fichesController = controllers && controllers.fiches ;
/**
[...]
**/
  // fiches routes
  if (fichesController) {
    app.get('/fiches', fichesController.all);
  } else {
    console.warn(unsupportedMessage('fiches routes'));
  }
};
```
## Question
**How to create a new table with the mongoose schema and what did I do wrong?**
--> Plus when I look for the compiled code I don't find the fiches-compiled files in it like for TopicSchema : 
### TopicSchema : 
¦_ _ compiled/db/mongo/models
¦_ _ _ _ _ topics-compiled.js
¦_ _ _ _ _ topics.js
¦_ _ _ _ _ topics-compiled.js.map

But I find them in the server folder: 
### FicheSchema
¦_ _ server/db/mongo/models
¦_ _ _ _ _ fiches-compiled.js
¦_ _ _ _ _ fiches.js
¦_ _ _ _ _ fiches-compiled.js.map

Hope I was clear enough, thank you in advance!
(Sorry for long post)

**Comment by psimyn** [comment]
```
export default mongoose.model('Fiche', FicheSchema);
```

you have this in `controllers/fiches.js`, but it should be at the bottom of `models/fiches.js`

**Comment by hhelb** [comment]
thanks for your reply @psimyn.
Unfortunataley it was a copy/paste mistake, the  `export default mongoose.model('Fiche', FicheSchema);` line is indeed at the bottom of `models/fiches.js`..
I am sorry, I have edited my post.

**Comment by hhelb** [comment]
Hey @psimyn.
I decided to do a fresh start and manage to reproduce the error. 
It seems like when I edit the schema,  a  new "fiches-compiled.js" is created just  below the fiche.js : 

![errormongoosenewcompiled](https://cloud.githubusercontent.com/assets/5981621/20559267/f5a89230-b173-11e6-90cb-5f993af7a409.png)

This new compiled file will be in conflict whith the first "fiches-compiled" : 

![errormongoosepreviouscompiled](https://cloud.githubusercontent.com/assets/5981621/20559268/f8d68200-b173-11e6-9fb7-d19dd6f1fb01.png)

All I have to do is to delete this new file every time I make changes.. (It's really annoying)
 
FYI, I am using webstorm. 
So Is webstorm creating automatically this file with the help of IDK what (babel/webpack?)

I will try with another text editor and keep you informed.

Any guesses here ?

**Comment by slavab89** [comment]
The problem that you're having is that you're trying to register mongoose Scheme more than once.
The first time is: 
https://github.com/reactGo/reactGo/blob/master/server/db/mongo/connect.js#L24
And the second time is in your controller.

Node caches the file based on its path so the controller loads ```../models/fiches``` and the connect file loads ```__dirname/models/fiches```
I am actually not 100% how does it work with Topics as the code seems the same XD
If you need the model itself you can try to work with ```mongoose.model('Fiches')``` in the controller as it will return the compiled mongoose scheme without the second init
