### ISSUE TITLE
Create separate repositories for examples

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#728]
In line with https://github.com/reactGo/reactGo/issues/706, also https://github.com/reactGo/reactGo/issues/372#issuecomment-236558777

We should create separate repositories for:
- MongoDB example (with voting + auth example)
- Postgresql example (with voting + auth example)

+ Add the links to our main README.md for people refer to them.

+ Set this main _light_ repository as upstream

And that leads to the hard bit...

- **What should we name them?**
- **Is this the right way to separate them?**

Anyone with opinions? I don't think we can comfortably remove code + examples in this repository without pointing people to the proper examples for now.

**Comment by psimyn** [comment]
Create branches for each? Naming at least is then as easy as "mongo", postgoat etc 

Can still link, keeps everything a bit more contained

**Comment by choonkending** [comment]
Good first step!
