### ISSUE TITLE
reactGo next branch

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#729]
In scope:
**Client**
- Remove `/vote`, `/about`, `/login` routes
**Server**
- Remove database dependency
- Remove passport authentication

Out of scope:
- If any changes arise that can clean the codebase that is not specific to 2.0, we should create an issue and solve in `master` before merging back into `v2`
- Migrating master to other repository #728

**Comment by psimyn** [comment]
Do you want to remove stuff or add a "init" style command to delete all default included routes and components? 

That way you have a working demo for people to tinker with, and can make barebones if needed. Sometimes a too-bare boilerplate can be a bit overwhelming

**Comment by choonkending** [comment]
> Do you want to remove stuff or add a "init" style command to delete all default included routes and components

I initially wanted to try just having a bare bones branch + just removing things.

> Sometimes a too-bare boilerplate can be a bit overwhelming

Good point @psimyn. We can possibly write an `init` command that deletes the routes + components. 

My only concern is that deleting + modifying code is not going to be straight forward as we think. 

What I plan to do:
1. I will probably attempt a v2 branch
2. We should be happy and clear with what our "end goal" of v2 should be - stateless and deployable app that is barebones.
3. We can go through the commit history of what was deleted + modified
4. We then do a spike around what's involved in converting master -> v2, which might involve:
   - Deciding how we can `delete` or `modify` our code with a command (I have not done this before, but I imagine a bash script or similar?)

If we find it necessary to modify our code, it might also indicate that our code is too tightly coupled for it to be easily changed. 

What do you think?

**Comment by choonkending** [comment]
Closing as we already have a project wall for this https://github.com/reactGo/reactGo/projects/1
