### ISSUE TITLE
Better webpack configurations

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#735]
# Why
- I think we can still simplify our webpack config a bit further

# Proposals
- Use `CommonChunksPlugin` if we have a `vendor` bundle + manifest
- output files should have a `chunkhash` for caching
Read more about it [here](https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95#.9n3sl4cp6)
- Use [webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin) for referencing our output compiled file in the server side.

**Comment by ZeroCho** [comment]
@choonkending What is that webpack-manifest-plugin for? I visited that github page but I cannot get why it is needed.

**Comment by choonkending** [comment]
Good question (and sorry about the bad description)!

Currently our webpack config looks something like this:

```js
    output: {
      // The output directory as absolute path
      path: assetsPath,
      // The filename of the entry chunk as relative path inside the output.path directory
      filename: '[name].js',
      // The output path from the view of the Javascript
      publicPath: publicPath

    },

```

For a production build, it will always output as a fixed name. This is OK, but we're not really leveraging what webpack gives us as an option - adding chunkhashes to names for cache busting.

```js
    output: {
      // The output directory as absolute path
      path: assetsPath,
      // The filename of the entry chunk as relative path inside the output.path directory
      filename: '[chunkhash]-[name].js',
      // The output path from the view of the Javascript
      publicPath: publicPath

    },
```

Prefixes the JS file with a chunkhash, e.g. `ab1321312-main.js`, so you can have caching for all your assets. When you deploy the next round (and you have code changes), this `chunkhash` will change and browsers won't be using an older version of your website!

Problem with this is:
- We would need to reference the proper file names in [pageRenderer](https://github.com/reactGo/reactGo/blob/master/app/utils/pageRenderer.js#L31)
- We would need to require the proper file name in [server/index](https://github.com/reactGo/reactGo/blob/master/server/index.js#L8)

Which is why having ManifestPlugin gives us access to the file names output by webpack! 🎉

**Comment by ZeroCho** [comment]
Aha understood! Thank you!

**Comment by choonkending** [comment]
Possibly upgrade to #743 in the process

**Comment by ZeroCho** [comment]
@choonkending is webpack-manifest-plugin similar with [assets-webpack-plugin](https://github.com/kossnocorp/assets-webpack-plugin)
