### ISSUE TITLE
Spike on react-hot-loader 3

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#736]
# Why
- Our babel plugins are all over the place
- react-hot-loader seeks to combine the approaches in hot loader 1 and react-transform-hmr in 1 place
- We should try it out - most of the issues in the PR seem to be ironed out already

# How
Refer to any of [these](https://github.com/gaearon/react-hot-loader/tree/master/docs#starter-kits) and try them out

Also refer to this - https://github.com/gaearon/react-hot-boilerplate/pull/61

Hopefully get to have our babel plugins in 1 place - instead of in `.babelrc` and `webpack` configs.

Will document as I go!

**Comment by choonkending** [comment]
Here is a spike of the spike so far.

https://github.com/reactGo/reactGo/compare/master...choonkending:react-hot-loader-3

Problems:
- Refreshes the entire page when I change a component 😢

**Comment by ZeroCho** [comment]
This will be the hardest part...

**Comment by alex-shamshurin** [comment]
@ZeroCho The same is for me. I did everything like in tutorial but it reloads the page
