### ISSUE TITLE
Es6 Promise polyfill 

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#739]
Continuing the discussion in https://github.com/reactGo/reactGo/pull/732#issuecomment-263272260

# Type: Bug

- We are calling `polyfill` multiple times and inconsistently
- Should we stick we the current polyfill or use a webpack plugin?
   - I'm leaning with sticking with a polyfill dependency because I'm afraid webpack is doing wayyyy too much (but I'm not entirely sure)

@ZeroCho @lapinskicho

**Comment by ZeroCho** [comment]
```
entry: {
    app: ['babel-polyfill', 'eventsource-polyfill', './client', hotMiddlewareScript],
  },
```
this is my webpack.config.dev-client.js. and **not** for server.
eventsource-polyfill is for IE

**Comment by lapinskicho** [comment]
@choonkending I am new to the package and still picking up the nuts and bolts of it, but I think it is good to use babel-polyfill to emulate a full es6 environment (over es6-promise to just emulate es6 promise) as down the road, developers may use additional es6 features (e.g. generators), so it is more for "forward-compatibility."

**Comment by yowakita** [comment]
@choonkending I created a PR to add `babel-polyfill` and `eventsource-polyfill` to the Webpack configurations.
#808
