### ISSUE TITLE
Page "flashes" when it first loads because <style> tag is added via Javascript

### ISSUE THREAD

**Issue by rclmenezes** [reactGo/reactGo#762]
### Description
- Type: Question

## Question

The page seems to "flash" when it first loads because the server-rendered content is unstyled. It seems that main.css is added to `<head>` via Javascript.

Is there an easy way to remove this flashiness by adding main.css to `<head>` without JS?

**Comment by ZeroCho** [comment]
It's related with #289 and only happens in dev environment.

**Comment by rclmenezes** [comment]
Thanks! Sorry for duplicate. Couldn't find it.
