### ISSUE TITLE
Webpack doesn't rebuild/reload inside docker on macOs machine during  'npm run dev'...

### ISSUE THREAD

**Issue by iolp** [reactGo/reactGo#767]
I have placed this repository inside docker. When i change something, webpack doesn't rebuilds on macOs. But everything works great on linux. Why?

**Comment by slavab89** [comment]
Does it run somehow differently inside mac? Its a docker container so it should work exactly the same?
Are your volumes set up correctly? nodemon is running etc.?

**Comment by psimyn** [comment]
Are you using Docker Machine or Docker for Mac? I recall virtualbox having issues with inotify events (which trigger the changes). Some googling around that might help, otherwise  `npm run dev` from inside the container should work

**Comment by slavab89** [comment]
We're cleaning the project and closing issues.
We didnt hear back from you about this so i'll assume it was resolved.
If you still have any issue, please comment here or open a new one
