### ISSUE TITLE
greenkeeper is out of control

### ISSUE THREAD

**Issue by psimyn** [reactGo/reactGo#774]
Currently adding more noise than value for me. I think either disable or start merging the PRs

Anyone for/against?

**Comment by choonkending** [comment]
I think we should:
- disable greenkeeper
- merge existing PRs
- possibly enable greenkeeper after our refactors

**Comment by ZeroCho** [comment]
@psimyn @choonkending I also think that greenkeeper is too noisy.
It just gives us information about new release, but doesn't make sure that new package is suitable for reactGo.

**Comment by choonkending** [comment]
Alright I _think_ I've disabled this

**Comment by choonkending** [comment]
I'm closing this, but if greenkeeper comes again, please re-open this issue and yell at me.

**Comment by choonkending** [comment]
I think I failed to disable greenkeeper because I passed in the wrong slug - since I now push from my fork rather than to the main repo.

**Comment by choonkending** [comment]
Now I have truly disabled it! 

`greenkeeper --slug=user/repo disable` did the trick
