### ISSUE TITLE
import and customise bulma framework classes in css/ folder files

### ISSUE THREAD

**Issue by IzaGz** [reactGo/reactGo#775]
I'm trying to add bulma framework (or any other, material, leaf, bootstrap). Now i require it in app/client.js with this ' require("!style!css!bulma/css/bulma.css"); '. How can I customize bulma css? 
is there a way, somehow, if i 'll make @import inside files(inside one or many) in existing css folder? change variable css for .button class for example? Can i resolve this in the webpack config?

**Comment by slavab89** [comment]
We're cleaning the project and trying to close issues.
You should be able to use the `:global` scope of PostCSS to change classes. By the looks of it, you're loading `bulma.css` without webpack styles so the classes stay the same.
Another option is to just copy the CSS to your project and edit it there.
If you still have any issue, please comment here or open a new one.
