### ISSUE TITLE
Fails to properly create necessary tables with Postgres

### ISSUE THREAD

**Issue by pruhstal** [reactGo/reactGo#776]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug

---------------------------------------------------------------
## Bug
**Expected Behavior**
Running `npm run sequelize db:migrate` should create the relations in the DB.

After following this instructions here: https://github.com/reactGo/reactGo/blob/master/docs/databases.md and running `npm run sequelize db:migrate` it seems to run properly. The tables are created. 

**Actual Behavior**
After following this instructions here: https://github.com/reactGo/reactGo/blob/master/docs/databases.md and running `npm run sequelize db:migrate` it seems to run properly. The tables are created. 

However, when I try to select anything from them, it says that the relations don't exist.

<img width="378" alt="screen shot 2016-12-15 at 5 56 13 pm" src="https://cloud.githubusercontent.com/assets/624807/21249033/109cf094-c2f0-11e6-9ed9-0d46af4f0f8c.png">

**Steps to Reproduce**

1. Git clone the repo
2. `npm install`
3. Run:

```
createuser root
createdb react_webpack_node_development # or test/production
npm run sequelize db:migrate
```

Then

`DB_TYPE="POSTGRES" npm start`

Then go to `localhost:3000`

The router will throw an error `Cannot GET /`

and see the following output:

```
> react-webpack-node@2.0.1 start /Users/parkerruhstaller/Sites/reactGo
> cross-env NODE_ENV=production node compiled/index.js

--------------------------
===> 😊  Starting Server . . .
===>  Environment: production
===>  Listening on port: 3000
===>  Using DB TYPE: POSTGRES
===> 🚦  Note: In order for authentication to work in production
===>           you will need a secure HTTPS connection
--------------------------
(node:29663) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Failed to prune sessions: relation "session" does not exist
Executing (default): SELECT 1+1 AS result
Successfully connected to sequelize database
Failed to prune sessions: relation "session" does not exist
```

---------------------------------------------------------------

Has anyone got this working properly with postgres? I didn't try it with mongo and it doesn't work with no db.

**Comment by electrostaticfleece** [comment]
For your query have you tried to add double quotations to delimit the identifier: 

`select * from "Users"`

Given that you're getting a` failed to prune sessions: relation "session" does not exist` warning and you're able to connect to the database, it might not hurt to double check that the production database (react_webpack_node_production) has had the migration run on it as well.

**Comment by slavab89** [comment]
We're cleaning the project and closing issues.
We didnt hear back from you about this so i'll assume it was resolved.
If you still have any issue, please comment here or open a new one
