### ISSUE TITLE
reactGo + acuityscheduling  = error w/ json-loader for webpack

### ISSUE THREAD

**Issue by phoniks** [reactGo/reactGo#782]
### Description
- Type:  Question

I tried installing [this](https://github.com/AcuityScheduling/acuity-js) package within reactGo, and it seems that the webpack config is incompatible.  Specifically the json-loader seems to break.
---------------------------------------------------------------
## Bug
**Steps to Reproduce**

Load up a reactGo instance and install dependencies
Then `npm i --save acuityscheduling`
Then `npm run dev`
Try to add this example script somewhere 

``` 
var Acuity = require('acuityscheduling');

var acuity = Acuity.basic({
  userId: [[app:username]],
  apiKey: '[[app:password]]'
});

acuity.request('appointments', function (err, res, appointments) {
  if (err) return console.error(err);
  console.log(appointments);
});
```
----------------------------------------------------------------
-----------------------------------------------------------------

## Question

**How to?**

Is there a way to change the webpack config to make this work? Any ideas on how to make them play nicely together?

**Comment by ZeroCho** [comment]
#806 webpack@2 might be solve this issue because webpack@2 handles json-loader internally

**Comment by slavab89** [comment]
We're cleaning the project and closing issues.
The project now uses webpack 2 therefore i'll assume this issue was resolved.
If you still have any issue, please comment here or open a new one
