### ISSUE TITLE
Help using react-ace

### ISSUE THREAD

**Issue by tabouzeid** [reactGo/reactGo#783]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Question
- Related Issue: `none`

-----------------------------------------------------------------

## Question

**How to?**
i need to be able to use the code editor react-ace but it seems to not work... 

i'm told that because it's created on the client so it's not supported anymore since everything is done on the server. is there a workaround for it to make it work? or maybe alternatives that i can use?

also how do i refer to the bootstrap css classNames?

**Comment by ZeroCho** [comment]
@tabouzeid Do you mean that you cannot use that editor because that doesn't support rendering on server?

**Comment by tabouzeid** [comment]
Yes i've included the error below. After looking online i found this thread, [https://github.com/thlorenz/brace/issues/40](url) and this message seems to state the problem... 

> I've looked at your project, and correct me if I'm wrong, but it looks like you are rendering your React app server-side. Node doesn't have a window object, which is why this is failing. You'll see if you run your gulp browserify task, that the client-side app JS compiles just fine; it's your nodemon and src/server.js that is blowing up. Has nothing to do with Babel. IMO, it doesn't make any sense to try to render Ace server-side; it only has meaning on the client-side.

i'd appreciate any insight into how to resolve this issue if there is a way... and thanx in advance

==================
`/reactGo/node_modules/brace/index.js:88
        return callback && callback.apply(null, params) || true;
                                    ^
ReferenceError: window is not defined
    at /reactGo/node_modules/brace/index.js:18673:26
    at _acequire (/reactGo/node_modules/brace/index.js:88:37)
    at Object.acequire (/reactGo/node_modules/brace/index.js:93:26)
    at /reactGo/node_modules/brace/index.js:18671:21
    at Object.<anonymous> (/reactGo/node_modules/brace/index.js:18678:15)
    at Module._compile (module.js:571:32)
`

**Comment by ZeroCho** [comment]
First of all it is not a ReactGo issue. It happens every react editor that depends on DOM.
There are two ways to solve this as far as I know

First, only load editor when it is client
```
let ReactAce;
if (__CLIENT__) {
  ReactAce = require('react-ace');
}
```

Second, load asynchronously after components mounted.
```
componentWillMount() {
    const { postingReducer, params } = this.props;
    const post = postingReducer.post;
    this.loadEditor().then(({ RichTextEditorModule }) => {
      let defaultValue = '';
      if (params.id && post) {
        defaultValue = postingReducer.post.content;
      }
      this.setState({
        RichTextEditor: RichTextEditorModule,
        initialValue: defaultValue,
        value: defaultValue && __CLIENT__ ? rawFromHTML(postingReducer.post) : this.state.value,
      });
      if (__CLIENT__) {
        window.addEventListener('scroll', this.onScroll);
      }
    }).catch(err => console.error(err));
  }

loadEditor = () => (
    new Promise((resolve, reject) => {
      try {
        require.ensure([], (require) => {
          const RichTextEditorModule = require('react-draft-wysiwyg').Editor;
          resolve({ RichTextEditorModule });
        });
      } catch (err) {
        reject(err);
      }
    })
  );
```

**Comment by slavab89** [comment]
We're cleaning the project and closing issues.
I'll assume it was resolved with the great answer above.
If you still have any issue, please comment here or open a new one
