### ISSUE TITLE
Bug: Todos not persisting in mongo DB

### ISSUE THREAD

**Issue by gauravarora91** [reactGo/reactGo#784]
git clone
npm install 
npm run dev

> react-webpack-node@2.1.0 dev /Users/**/reactGo
> cross-env NODE_ENV=development nodemon

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/**/reactGo/app/utils/**/* app/server.jsx app/routes.jsx /Users/**/reactGo/server/**/* webpack/webpack.config.dev-client.js webpack/webpack.config.dev-server.js .stylelintrc
[nodemon] starting `npm run build:dev && node compiled/server.dev.js`

> react-webpack-node@2.1.0 build:dev /Users/**/reactGo
> cross-env NODE_ENV=development webpack ---debug --colors --display-error-details --config ./webpack/webpack.config.dev-server.js

Hash: 401b2505459a9dbe1331
Version: webpack 1.14.0
Time: 11492ms
            Asset     Size  Chunks             Chunk Names
    server.dev.js   876 kB       0  [emitted]  server
server.dev.js.map  1.01 MB       0  [emitted]  server
    + 309 hidden modules
--------------------------
===> 😊  Starting Server . . .
===>  Environment: development
===>  Listening on port: 3000
===>  Using DB TYPE: MONGO
--------------------------
===>  Succeeded in connecting to mongodb://localhost/ReactWebpackNode
webpack building...
webpack built 32af108534092747fe2b in 9423ms

Problem is mongo has todos still its not showing todo's, on first render as well as via routing. Nothing comes in state as well.

**Comment by choonkending** [comment]
@gauravarora91 Thanks for reporting. I can confirm that this is happening to me as well.

**Comment by choonkending** [comment]
Documenting our discussion here https://github.com/reactGo/reactGo/pull/780/files#r94002355

**Comment by gauravarora91** [comment]
Thanks!
