### ISSUE TITLE
Write good  tests

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#785]
We've had some regressions lately, mainly due to the lack of good test coverage. As a rule of thumb, we should be writing tests that go with the code from now onwards.

Basic guideline to test writing:
- It should not be coupled to the implementation of the code, i.e. it should not need to know the internals of the component/module

Scope:
- Client and server-side

**Comment by ZeroCho** [comment]
I think we need to test server side codes too.

**Comment by choonkending** [comment]
Fix failing tests as well #790
