### ISSUE TITLE
CSS Modules & components structuring

### ISSUE THREAD

**Issue by omidahourai** [reactGo/reactGo#787]
### Description
- Type: Question

**Is it better practice to keep non-common css with their components / containers?**
I've recently found that this makes things easier, and feels more natural with css modules. For example,

I have a button:
```
app/components/Button/index.jsx
app/components/Button/styles.css
```

I can import it with:
`import Button from '../components/Button';`

and in Button.jsx:
`import styles from './styles';`

Feels more right to me :p

**Comment by choonkending** [comment]
Yep, I've personally been using styles within the same component directory as you have mentioned, and it seems right to me as well. I would even go so far to put tests, reducers, containers within the same component if it makes sense!

We've been looking at a similar structure, but currently am working on cleaning up our repository before moving on to that! Thanks for raising this as an issue!

**Comment by ArdentKid** [comment]
Although when using vscode, it's not as nice to see the filename highlighted instead of the component folder/ name. Wonder if there's a plugin for that.

**Comment by psimyn** [comment]
there is https://atom.io/packages/nice-index for atom which shows folder name if you're editing an index.* file.

otherwise you can use `index.js` just for exports, then keep all the file names correct

```
app/components/Button/index.jsx
app/components/Button/Button.jsx
app/components/Button/Button.css
```

**Comment by slavab89** [comment]
We're cleaning the project and closing issues.
I'll close this as in the end its a user/team preference. Feel free to continue discussing it.

Myself, i'm also using the "css beside component" convention, i also think its cleaner and readable
