### ISSUE TITLE
Use base url for reactGo app

### ISSUE THREAD

**Issue by mhlavacka** [reactGo/reactGo#793]
## Question

I need to serve app under base url ex. `http://myserver:3000/base_url/` like ex. google runs google maps under `https://google.com/maps`

I've tried to add base url to `server/config/express.js` doing the following, but didn't achieve any results:

` app.use('/base_url', express.static(path.join(__dirname, '../..', 'public')));`

What's the way to achieve setting base app URL in reactGo?

**Comment by lapinskicho** [comment]
Try changing  { node: { __dirname: false } } to true in webpack/*.js and see if that's what you want to achieve.

See https://webpack.github.io/docs/configuration.html under node section for what true/false does on __dirname.

**Comment by lapinskicho** [comment]
Also please refer to issue #797 to see if you need to make other changes.

**Comment by lapinskicho** [comment]
If you are not trying to get the exact path of your current file, avoid __dirname and use process.cwd(), such as:
path.join(process.cwd(), 'public')

**Comment by mhlavacka** [comment]
Thanks @lapinskicho. Surprisingly this did the job:
```
<Route path="/base_url" component={App}>
    <Route path="/search" component={Search} />
</Route>
```
