### ISSUE TITLE
webpack server-side rendering options: node: { __dirname: false }

### ISSUE THREAD

**Issue by lapinskicho** [reactGo/reactGo#797]
I saw a change has been made to express config after adding the webpack option { node: { __dirname: false } }

server/config/express.js:28:  app.use(express.static(path.join(__dirname, '..', 'public')));

Due to the option, __dirname is evaluated after the files are webpack-ed to the compiled/ directory. 
Is it more flexible to set the option as { __dirname: true } instead?  New developers using reactGo may not know __dirname is not evaluated relative to the file/context, and may waste time debugging (like I did) to configure out the option is the culprit.

**Comment by choonkending** [comment]
@lapinskicho Thanks for raising this! Excellent detective work! 

Yes, that seems reasonable. I initially had set `__dirname: true`, but I cannot remember why it did not work. Will have to look at this (along with the #796 ) issue you raised tomorrow!

**Comment by ZeroCho** [comment]
I remember that when setting dirname to true, it breaks webpacking on windows.
I saw some errors related to resolving path.

**Comment by lapinskicho** [comment]
Not sure about the Windows issues, but in general, setting dirname to true may cause other "unexpected" problems, as webpack won't return __dirname a full path anymore, it may just be a relative path, so some other things need to be taken care of... but I think it is better than just setting it to false and many users may scratch their heads if things don't work the way they expect (as it takes time to nail down to this __dirname problem).
