### ISSUE TITLE
Improve UI design + content of test website

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#799]

**Comment by ArdentKid** [comment]
Oh just saw this lol. Recommending [react-toolbox integration](#791) would work well imo (even with the default theme).

**Comment by lapinskicho** [comment]
I would suggest a "marketing" banner for reactGo and an improved About section to summarize the functionality of the boilerplate too.  Not sure if it is "UI design" but I think it helps to give developers a better idea what reactGo is when they happen to run into the demo without landing on this github page first.

**Comment by choonkending** [comment]
Definitely! I've been meaning to change the content a bit to be more descriptive.
