### ISSUE TITLE
Rename preRenderMiddleware -> fetchDataForScreen

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#804]
Raised in https://github.com/reactGo/reactGo/issues/757#issuecomment-271077728

I think given that this is a critical part of reactGo, it ought to have a more intention-revealing name.

**Comment by ArdentKid** [comment]
perhaps "fetchDataForRender"?

**Comment by choonkending** [comment]
@ArdentKid Good suggestion! I considered that carefully. Although we are technically fetching data to be rendered, in the client side's case, we are using it to change the store state, which causes a re-render.

I've created a PR calling it `fetchDataForRoute`. From another perspective, we can also think of the responsibility of this module as `fetchData` for `route`.
