### ISSUE TITLE
We can remove babel-plugin-transform-decorators-legacy

### ISSUE THREAD

**Issue by ZeroCho** [reactGo/reactGo#813]
**Reason to enhance/problem with existing solution**
We don't use decorator currently. We can kill one of our dependencies.

**Suggested enhancement**
Remove it!

**Pros**
One less dependencies

**Cons**
Maybe need decorator later.

**Comment by choonkending** [comment]
YESS!!! I love decorators!

**Comment by choonkending** [comment]
I mean, rolling your own decorator instead of the syntactic sugar
