### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by dimitri-a** [reactGo/reactGo#829]
## Question
I am running 'npm run dev' in windows 7, node v.5.6,npm  v. 3.6.0, and getting this error in the commandline:

webpack\webpack.config.js:19
module.exports = (env = '') => {
SyntaxError: Unexpected token =
  at exports.runInThisContext (vm.js:53:16)

How can I fix this?

**Comment by choonkending** [comment]
I believe it's the version of node you're on that does not support default function parameters in ES6.
http://node.green/

Try node >=  6 and let me know how that goes!

**Comment by caglar-senel** [comment]
Indeed it is, I had the same for node 4.2.6. I think it is worth pointing in readme that you will need a node version => 6.
