### ISSUE TITLE
Resolving paths with `process.cwd()` is a bit flaky

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#830]
# Problem 
`process.cwd()` depends on where the application is run from. So if you run the application from a different folder, things will break because you resolve your paths that way.

Read more [here](http://stackoverflow.com/a/31436403/1710968)

For computing files, I think we should still resort to `__dirname`.

**Comment by GGAlanSmithee** [comment]
In my experience, `process.cwd()` is actually more reliable than `__dirname` when working with webpack. Especially when plugins, rules etc are in another directory than the webpack config itself. The _only_ caveat with `process.cwd()` AFAIK is that you have to run it from the root directory. Maybe there could be some problems in the context of testing etc, but I have never had any actual problems with using `process.cwd()`.

**Comment by choonkending** [comment]
Right on. Changing dirname to false makes things so much more confusing and harder to follow. Alright closing. Good discussion!!
