### ISSUE TITLE
FOUC Issue

### ISSUE THREAD

**Issue by jpadula** [reactGo/reactGo#831]
[files.zip](https://github.com/reactGo/reactGo/files/785950/files.zip)

### Description
- Type: Question

---------------------------------------------------------------
## Bug
I am almost finishing a system using this skeleton and I am having a FOUC issue in production (Flash of Unestyled Issue). I just tried with many changes in the webpack but I cant solve it.

I attached my two webpack files (common and prod). I am generating two files (one admin.css and another public.css since we have two different templates per each role).

Anyone knows what can I do to solve this?

Thanks in advance,

Jorge

**Comment by slavab89** [comment]
Something similar was asked before https://github.com/reactGo/reactGo/issues/289
We're trying to clean up the project and close issues.
If you still experience this or have an issue please comment or open a new one.
In case you've already solved this, it would be great to have the solution here.
