### ISSUE TITLE
HMR requires full reload when changes to CSS are made

### ISSUE THREAD

**Issue by gittestcoder** [reactGo/reactGo#834]
Hey there, 
I noticed that when you change your CSS it requires a full reload. This is the console's output:

>  The following modules couldn't be hot updated:
> ./~/css-loader?{"localIndentName":"localIdentName=[name]__[local]___[hash:base64:5]","sourceMap":true,"modules":true,"importLoaders":1}!./~/postcss-loader?{"sourceMap":true,"plugins":[null,{"version":"5.2.15","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"postcss-cssnext","postcssVersion":"5.2.15"},null,{"version":"5.2.15","plugins":[null,null,null,null]}]}!./app/assets/styles/base.pcss

Any ideas on how to fix this? It's pretty annoying

**Comment by Cleanshooter** [comment]
Hmmm... I can't replicate this. What's with the .pcss file extension on your base file (is that something special for postcss?) I've never seen it before and the webpack config only looks for .css files so... that might be it...

**Comment by gittestcoder** [comment]
The .pcss file extension is for postcss, so my text editor doesn't complain about weird looking postcss syntax. Either way that doesn't affect this issue.

I actually figured out the problem to this issue and figured out a workaround. If you import a css file to use for a stateless component (like the client.jsx file), it's not able to hot reload. So everytime you make a change to that css file the whole component will need to do a full reload. The solution is to change it to a regular React component.
