### ISSUE TITLE
Add Dynamic meta title 

### ISSUE THREAD

**Issue by ghost** [reactGo/reactGo#842]
## Question

Problem: When I update the title from this.state.title from some api, it is not updated. This is especially important for me to share on Facebook, but only the old title is displays.

**Comment by ZeroCho** [comment]
you should use **react-helmet** to manipulate meta tags. Changing it via this.state.title does not help.

**Comment by kamish770** [comment]
i'm using  react-helmetץ. it's part of the reactGo starter, but I want that the title will be accordance  the title of the post. for example: 

`getMetaData() {
    return {
      title: this.pageTitle(),
      meta: this.pageMeta(),
      link: this.pageLink()
    };
  }

  pageTitle(title) {
    return this.state.title + ' | reactGo';
  }

render() {
      return (
      <Page {...this.getMetaData()}>
        <QuestionContainer {...this.props} />
      </Page>
    );
  }

`

in page.jsx: 

`onst Page = ({ title, link, meta, children }) => {
  return (
    <div>
      <Helmet title={title} link={link} meta={meta} />
      { children }
    </div>
  );
};

Page.propTypes = {
  title: PropTypes.string,
  link: PropTypes.array,
  meta: PropTypes.array
};

export default Page;`

**Comment by choonkending** [comment]
@kamish770 Thanks for raising this. Where are you deriving your state from? 

You should be able to pass your title as a prop to `Page` regardless of where you derive it from. 

Do you have an example repo up somewhere? Otherwise it might be a bit tricky to understand.

**Comment by kamish770** [comment]
[https://github.com/kamish770/reactGotest/blob/master/app/pages/Question.jsx](url)

here. Thanks!

**Comment by zeeshanjan82** [comment]
@kamish770 I am facing the same issue were you able to resolve it?

**Comment by zeeshanjan82** [comment]
I am trying to apply the blog title dynamically on the page with this code:

```
class Blog extends Component {
  getMetaData(blog) {
    return {
      title: this.pageTitle(blog),
      meta: this.pageMeta(),
      link: this.pageLink()
    };
  }


  pageTitle(blog) {
    return blog.blogName;
  }

  pageMeta() {
    return [
      { name: 'description', content: 'A reactGo example of a voting page' }
    ];
  }

  pageLink() {
    return [];
  }

  render() {
    const {blog, blogs } = this.props;
    return (
      <Page {...this.getMetaData(blog)}>
        <BlogContainer {...this.props}/>
      </Page>
    );
  }
}

function mapStateToProps(state) {
  return {
    blog: state.blog.blog.blog,
    blogs: state.blog.blog.blogs
  }
}

export default connect(mapStateToProps, { })(Blog);
```
I can see that the title is applied but when I 'view source' the page I see the default title.

**Comment by vsc-github** [comment]
Struggling with the same issue. It is possible to pre-fill meta tags before sending the first rendered output from server via Helmet. We probably need to configure it differently.

@zeeshanjan82  Did you find a workaround?

**Comment by LucienPerouze** [comment]
Hi, maybe late ...
A bot (facebook, twitter, google, ...) will not uses javascript on their environment to render your app so there is no js pluggin that can do the trick on the client side. You have to render your page from the server. If you are on AWS s3 there is a easy way to solve this : https://medium.com/@lucienperouze/how-to-layout-facebook-shares-of-a-react-web-app-hosted-on-aws-s3-cloudfront-1ee146dbb5d2
