### ISSUE TITLE
Real class name in html

### ISSUE THREAD

**Issue by joinjoohny** [reactGo/reactGo#843]
Hello all ;)
How can I display a real class in html instead 
`_2HHJ_852M42LCiYML0PJN6 `
Thx!

**Comment by ZeroCho** [comment]
You should set `localIdentName` to `[name]` for production environment

**Comment by joinjoohny** [comment]
@ZeroCho Thx
It was a small mistake in the code`webpack/rules/css.js`
```js
const localIndentName = 'localdentName=[name]__[local]___[hash:base64:5]';
```
to
```js
const localIdentName = 'localdentName=[name]__[local]___[hash:base64:5]';

**Comment by slavab89** [comment]
Also fixed by https://github.com/reactGo/reactGo/pull/885
