### ISSUE TITLE
Get UserId of Currently Logged In User

### ISSUE THREAD

**Issue by darrindickey** [reactGo/reactGo#845]
I want to create a profile for users that they can update. I'd like to query the existing user data from the database and populate the profile form and let the user change the information. However, I can't seem to find a way to get the user id to query that data from the postgresql database.

Do I need to find a way to save it when the user initially logs in?

**Comment by slavab89** [comment]
Basically when you log in, your user information should be saved in the session.
Try to print out `req.user` and see what it contains (should contain the current logged in user)

**Comment by darrindickey** [comment]
It was coming up undefined. Thanks though.
