### ISSUE TITLE
Webpack loader issue - DeprecationWarning: loaderUtils.parseQuery()

### ISSUE THREAD

**Issue by slavab89** [reactGo/reactGo#848]
When running the project i see the following warning:
```
(node:19056) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
I've tried to add `process.traceDeprecation = true` to various places but for some reason it doesnt show which loader causes this issue.

Anyone knows how to fix this?

**Comment by ZeroCho** [comment]
One of loaders must be using `parseQuery` instead of `getOptions` but I searched all loaders(postcss, babel, style, json, css, url, file) I could not find `parseQuery`. That's very weird.

**Comment by slavab89** [comment]
If i search for `./parseQuery` in all node_modules the almost all loaders have a require to this. But i'm not sure if this is it - cause its in all loaders

**Comment by slavab89** [comment]
So, i've looked at this a bit further.
Seems to be happening on [babel-loader](https://github.com/babel/babel-loader/issues/392) plugin
It is fixed on version 7 that's on beta there.

So nothing much that we can do here other than wait =]

**Comment by GGAlanSmithee** [comment]
That's been bugging me too, thanks for diggin @slavab89

**Comment by slavab89** [comment]
So... getting back to this. Just after 2 days since i've close this issue. They've released version 7 of babel-loader.

I've updated to the latest version of all loaders and dont see this happen anymore

**Comment by zoruc** [comment]
@slavab89 I did the same thing and it fixed the issue thanks
