### ISSUE TITLE
Production to be served via http

### ISSUE THREAD

**Issue by FrenchBully** [reactGo/reactGo#862]
What are the steps needed to remove https for auth? 

Currently using Google passport, however I need to be able to serve the site over http.  This has to do with being able to connect and configure a external bluetooth device.

**Comment by choonkending** [comment]
@FrenchBully You would most likely have to change the following lines https://github.com/reactGo/reactGo/blob/master/server/init/express.js#L84-L88. Let me know if that helps

**Comment by FrenchBully** [comment]
thanks Ken, figured it out the other day.  Just missed it, but thanks for the pointer.
