### ISSUE TITLE
**How to use universal rendering for dynamic routes?**

### ISSUE THREAD

**Issue by hack0001** [reactGo/reactGo#863]
Can anyone point me in the right direction for dynamic routes that render on the server. I am trying to pass a :id param down through fetchData to the service call.

This is my routes.jsx
```
    <Route path="/" component={App}>
      <IndexRoute component={Vote} fetchData={fetchVoteData} />
      **<Route path="articles/:id" component={articles} fetchData={fetchArticleData} />**
    </Route>
```
I did try doing this in utils/fetchDataForRoute.js 

```
const defaultFetchData = () => Promise.resolve();

function fetchDataForRoute({ routes, params }) {
  const matchedRoute = routes[routes.length - 1];

  **if (params.id){
   const fetchDataHandler = matchedRoute.fetchData(params.id) || defaultFetchData;
   }**
  const fetchDataHandler = matchedRoute.fetchData || defaultFetchData;
  return fetchDataHandler(params);
}

export default fetchDataForRoute;
```

But the error given is saying that fetchDataHandler is not a function. I would be grateful for any advice on this

**Comment by GGAlanSmithee** [comment]
I am having a hard time seing this being the actual problem. Just to rule it out, can you try with another function that you know works? Like `fetchVoteData`.

**Comment by hack0001** [comment]
Thanks it did work and I have resolved the error now - you won't be surprised to hear that it was at my end.
