### ISSUE TITLE
Different components based on user role

### ISSUE THREAD

**Issue by slavab89** [reactGo/reactGo#864]
So this is a case that i arrived upon and i wanted to consult with you guys on it.

Say i have different roles for the users of the site, and the homepage for each role is different.
For example, if i enter the site as a "Teacher" then my '/' route will point to a list of classes that i teach
If i enter as a student, my '/' route will point to a list of grades that i have...

How would you do that kind of login?

I was thinking on 2 options:
1. Playing around with the routes.js file
2. Inside the main page component, return different component based on the role.

Bonus question: Has anyone played around with splitting the code into different bundles? I mean, have a "teacher" and "student" bundles, both having a third shared resource file but each of them only has the code that relates to them.... somehow....

**Comment by GGAlanSmithee** [comment]
Here are two active PRs pertaining to code splitting:

https://github.com/reactGo/reactGo/pull/823
https://github.com/reactGo/reactGo/pull/841

The way it's set up is that it's splitted on routes, so I'm not sure how to serve different bundles for the same routes, but is probably possible as long as you can differentiate it somehow. The `manifest.json` file contains all bundles.

**Comment by slavab89** [comment]
Thanks for the PR's i'll definitely look into them!

Regarding the different options, i also lean more towards option 2 as it seems that routes.js doesnt really need to concern itself too much with roles and users.
The code for the student parts will be available when logged in as a teacher but dont think its that bad.
