### ISSUE TITLE
Better RESTful API

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#865]
# Why

Ahem. Rabbit holes are easy to follow. 

Mentioned https://github.com/reactGo/reactGo/pull/853#issuecomment-297398803, my plan was to create a user service that acted as an interface to speaking to our API through our restApiClient. That way, our user action creators no longer needs to be aware of what calls are made or what underlying technology is used. Hooray.

I re-evaluated our current login, signup and logout url endpoints we make to the server, and did another round of reading for RESTful APIs. I recommend reading http://stackoverflow.com/a/2022938/1710968 in StackOverflow.

> In general, when you think you need more verbs, it may actually mean that your resources need to be re-identified. Remember that in REST you are always acting on a resource, or on a collection of resources. What you choose as the resource is quite important for your API definition.

This points out a flaw in our API. 

**Proposed Improvement**

Login - POST `/sessions`
Logout - DELETE `/sessions/id`
Register - POST `/users/`

Any thoughts or considerations? Always looking to improve our codebase.

**Comment by slavab89** [comment]
Currently its using /login /logout /signup. Dont see the real reason that its bad. Is it cause you dont want to have 3 distinct words for the "user management" flow?

/sessions might intent that you are actually using session in your app, but if for example you move to JWT, then you dont really have sessions..

**Comment by GGAlanSmithee** [comment]
Another question to ask is if RESTful is the way to go. Have you had any experience using `graphql` @choonkending ?

**Comment by choonkending** [comment]
@slavab89 Thanks for commenting! 

> Dont see the real reason that its bad. Is it cause you dont want to have 3 distinct words for the "user management" flow?

This is a bit of a tough one. I don't really have a **correct** answer for this. I don't think the current approach is wrong. My hope of making it more "RESTful" was to create a more standardised interface - which gives a clearer indication to developers of which this system's functionality actually is.

I've also had this discussion with a colleague of mine, and we came to the conclusion that no approach is more "correct". However, I still wish to drive this design to be more "uniform" and "expected" I guess. 

Excellent second point about JWT. I was hoping 🤞 that JWT had some other concept of "session", which would give us an idea of what to call the "resource". I am going to do some intense reading about authentication the next few days in hopes of driving a better design decision.

@GGAlanSmithee Good consideration! Yep, we've been using GraphQL at work, and it's a very interesting problem space (not without it's own design challenges). 

If we ever do decide to work with graphql, I see us implementing it on the API server layer. Perhaps we could still have authentication baked into our graphql response, but I think I'd like "authentication" to be it's own microservice, i.e. graphql server makes request to authentication service. There is no harm in trying to make our services more modular, because it makes it easier to use and remove/move around if we ever need to.
