### ISSUE TITLE
Coroutine regeneratorRuntime error (async await / yield)

### ISSUE THREAD

**Issue by omidahourai** [reactGo/reactGo#866]
**How to use coroutine on backend (async await / yield)?**

I get the following error when using Bluebird's Promise.coroutine on the backend: `ReferenceError: regeneratorRuntime is not defined` right when it hits that line of code.

Found [this help from the babel docs](https://babeljs.io/docs/plugins/transform-regenerator/) but it doesn't seem like reactGo even uses babel as a plugin?

Any help appreciated!

**Comment by ZeroCho** [comment]
We use `babel-loader` and you have to install package named `transform-regenerator` and  `transform-async-to-generator`. Then link it to babel-loader

**Comment by slavab89** [comment]
We're trying to clean up the project and close issues.
We havent heard back from you so i'll assume it was resolved.
In case you still have an issue, please comment here or open a new one.

**Comment by markolofsen** [comment]
I got an error when typing $yarn dev:
`ReferenceError: regeneratorRuntime is not defined`
