### ISSUE TITLE
Anyone have any luck deploying on Azure?

### ISSUE THREAD

**Issue by FrenchBully** [reactGo/reactGo#869]
Hi guys anyone have experience deploying on Azure?  I'm running into an issue, which looks like the node server isn't running.  The logs show no errors on the build. 

For 'Virtual applications and directories' I have it set to 'site\wwwroot' not sure if that could be the issue.

Web.config has been set for rewrite rules for server side routing.  Any thoughts welcomed.  Thanks in advance.

**Comment by slavab89** [comment]
In case you've already solved this, it would be great to have a PR that documents the process of it.
