### ISSUE TITLE
Build fails on latest version

### ISSUE THREAD

**Issue by gittestcoder** [reactGo/reactGo#870]
### Description
- Type: Bug

After downloading reactGo, running "npm install" and then "npm run build", I get the following error:

"'NODE_ENV' is not recognized as an internal or external command, operable program or batch file."

Any ideas?

**Comment by afganhalbana** [comment]
it would be fine on Linux, but if you are running on Windows you need to add set so it would be "set NODE_ENV=production"

**Comment by gittestcoder** [comment]
Huh... So I changed the build script and added "set" as you describe and then ran the "build" script and it worked. But when I deployed to heroku there was an error (I guess they use linux), so I removed "set" and tried deploying again and it worked. But the first time I tried deploying I didn't try anything and it didn't work for some reason? Do you need to run "build" before deploying to heroku?

Thank you for your response @afganhalbana

**Comment by GGAlanSmithee** [comment]
There is a missing `cross-env` in the `build` script, after the `&&`.

**Comment by gittestcoder** [comment]
So the full build script should look like this: "build": "npm run clean && cross-env NODE_ENV=production npm run webpack -- --env.browser && cross-env NODE_ENV=production npm run webpack -- --env.server"?

**Comment by GGAlanSmithee** [comment]
@gittestcoder Yes, please try that

**Comment by slavab89** [comment]
Was fixed in https://github.com/reactGo/reactGo/pull/916
