### ISSUE TITLE
preLoad (preFetch) vs componentWillMount

### ISSUE THREAD

**Issue by slavab89** [reactGo/reactGo#871]
So i was reading through the docs and issues of redux-saga and i've noticed several places where SSR is done.
In all of those places they were using componentWillMount to fetch the initial data from the API server. I was wondering, since here its implemented to do that using the preLoad logic, why is it like that? does it give some benefit over using componentWillMount?
Based on react site

> componentWillMount() is invoked immediately before mounting occurs. It is called before render(), therefore setting state synchronously in this method will not trigger a re-rendering. Avoid introducing any side-effects or subscriptions in this method.
> 
> This is the only lifecycle hook called on server rendering. Generally, we recommend using the constructor() instead.

Any thoughts?

**Comment by GGAlanSmithee** [comment]
Using `componentWillMount` is a pretty common practise for SSR. Also doing much of the same in a higher level of abstraction, using something like `graphql` with `apollo`/`relay` (which is what I do personally).

IMO, the difference is conceptual;

* Using `componentWillMount` etc, you are coupling data-fetching with a component, which goes in line with the co-location philosophy, which has gotten a lot of wind lately.
* Using pre-fetching (like in this project) you are coupling data-fetching with a route. This is a more old-school HTTP aproach.

I guess there is no way which is more right or wrong, but I am seeing more and more of co-location with everything from tests to data-fetching, and it looks to me like that is the way this project is inching towards too. If we were to move towards such an approach, I would suggest contemplating using something like `apollo`.

**Comment by slavab89** [comment]
Thanks a lot for the explanation. I'll close this as i got an answer but if anyone else wants to share what they think :D :D
