### ISSUE TITLE
Webpack deprecation error

### ISSUE THREAD

**Issue by zoruc** [reactGo/reactGo#874]
## Deprecation
When running npm run dev

**DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.**

## Question

How do you get rid of this warning? I've updated all the packages and loaders to points even further along than what you had in and I still get them is this something that is not configured correctly in the webpack configs

**Comment by GGAlanSmithee** [comment]
@zoruc unfortunatley, there's nothing to do about this, since it's one of the dependencies which is causing this error. We just have fto wait until they have updated accordingly.

See 848#issuecomment-295166577 from @slavab89

**Comment by jrodl3r** [comment]
the dep in question has been updated (7.0.0) and confirmed on fix too 👍
