### ISSUE TITLE
babel-preset-react-hrme is Abandoned

### ISSUE THREAD

**Issue by Cleanshooter** [reactGo/reactGo#877]
### babel-preset-react-hrme is Abandoned
- Type: Bug / Enhancement

I was upgrading some dependancies today and wanted to shed some light on something I'm currently working through to see if the community could provide some suggestions.  

babel-preset-react-hrme has been abandoned for quite some time and the author of react-transform-hmr is suggesting that you migrate your code to react-hot-loader v3.  

He's got a migration guide here: https://github.com/gaearon/react-hot-loader/tree/master/docs#migration-to-30

And what I can gleen from it after you do the install the only change we should need in the reactGo codebase is something like this:
webpack/rules/javascript.js
```javascript
const PATHS = require('../paths');

module.exports = ({ production = false, browser = false } = {}) => {
  // const enableHotModuleReplacement = !production && browser;
  // const createPresets = (enableHotModuleReplacement) => {
  //   const presets = ['es2015', 'react', 'stage-0'];
  //   return enableHotModuleReplacement ? ['react-hmre', ...presets] : presets;
  // };
  const presets = ['es2015', 'react', 'stage-0'];

  const plugins = production ? [
      'transform-react-remove-prop-types',
      'transform-react-constant-elements',
      'transform-react-inline-elements'
  ] : ['react-hot-loader/babel'];

  return {
    test: /\.js$|\.jsx$/,
    loader: 'babel-loader',
    options: {
      presets,
      plugins
    },
    exclude: PATHS.modules
  };
};
```
The reason I came across this is because the babel-preset-react-hrme library uses another old library called redbox. And in the most recent version of react you'll get this warning when using it because it's outdated...
**Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.**

**Comment by choonkending** [comment]
Thanks for raising this as an issue - and for outlining the solution!! Would you like to create a PR for this?

**Comment by Cleanshooter** [comment]
I'm still testing it... The above doesn't actually work :(.  I'll create a PR once I've got something legit 😁

**Comment by Cleanshooter** [comment]
#880 
Needs more work but I think I'm making progress any insight from the community would be great!
