### ISSUE TITLE
Strategy for managing `secrets.js`

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#882]
[this file](/reactGo/reactGo/blob/master/config/secrets.js) explicitly states that it is not to be committed to the repository. However, what is the recommended strategy is for doing so in a Heroku environment?

If you're doing auto deployment, or just pushing to heroku from CLI, how do you get that file on the server while keeping it out of the repo? Obviously, you can delete the file, add it to `.gitignore` and then re-add it. But that will keep it from being pushed to Heroku, no?

Thought this could use some clarifications...

**Comment by choonkending** [comment]
Ah I see. Perhaps that message was a bit misleading. What I meant is that the secret shouldn't be committed to a repository.

You could still have a file that accesses the variables from the runtime `process.env`. You can set the environment variables in Heroku dashboard and via command line. Check out [this](https://devcenter.heroku.com/articles/config-vars) link.
