### ISSUE TITLE
Images in Offline-Mode

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#883]
Noticed that aside from making requests, the app is almost entirely functional without an active connection on any device. The only issue so far is images, as they don't load.

Question is... Does anybody know a way to setup long-term cacheing, or max-age / expires to address this issue w/ images displaying offline?

Haven't tried it yet, but I wonder if setting images as static url's to CDN/S3 would do the trick?

Thx : )

**Comment by GGAlanSmithee** [comment]
Related to #361. @maintainers might I suggest https://github.com/NekR/offline-plugin? I can help implement it.

**Comment by psimyn** [comment]
Also possibly this

https://workboxjs.org/get-started/webpack
