### ISSUE TITLE
Checksum Console Warning

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#894]
Markup changes (ex: add `<div className={cx('foo')}></div>` to any component w/ style included) cause this checksum console warning:

<img width="822" alt="screen shot 2017-05-30 at 1 46 55 pm" src="https://cloud.githubusercontent.com/assets/869411/26604352/ee18d5ca-453e-11e7-9eb1-9f456d9d017f.png">

Current work-around is to restart DEV.

**Comment by slavab89** [comment]
Something [here](https://github.com/ReactTraining/react-router/issues/2036) might be able to fix it? Warning: pretty long 😆  (i didnt read it all yet)
[explanation](http://jeffhandley.github.io/QuickReactions/20-final-cleanup.html) on why this happens and what he did there (but its pretty old)

**Comment by slavab89** [comment]
So not sure if you want to close this or not but i've experienced a few times where this happened to me.

In all cases, it is actually a valid warning. It means that you have some code on the client that does not match what your server returns - which is true.
I've also had some cases (with `redux-form`) where this warning persisted even after a server restart but still it was a valid warning and i had to do something to make it go away correctly.

**Comment by slavab89** [comment]
We're trying to clean up the project and close issues.
We didnt hear back from you regarding this so i'll assume it was resolved.
In case you still have an issue with this, please comment here or open a new issue.
