### ISSUE TITLE
cors error, but in chrome network tab response is 200, and terminal curl works fine

### ISSUE THREAD

**Issue by rihannarickeminem** [reactGo/reactGo#896]
XMLHttpRequest cannot load URLURLURLURL. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
But in chrom network tab i see how the server responded with 200 .
Also with curl everything is workin fine.
What is the problem, how to fix it? May be it caused by server-side rendering? Or some helmet?
I have also created same issue in axios repo, `https://github.com/mzabriskie/axios/issues/942`

**Comment by slavab89** [comment]
CORS happens in the browser. You wont see this happening in CuRL.
Also, it is logical that in the network tab showing that the request passed :)
Check this https://github.com/reactGo/reactGo/issues/890 and look at the answers in the end, there are a few solutions there

**Comment by rihannarickeminem** [comment]
@slavab89  Thank you! But seem there is no answers , i ve tried to add `www` to requested url, but nothing helps.

**Comment by slavab89** [comment]
Try to add `express-cors` (easiest) as a middleware before your actual routes or try changing the endpoint that the frontend is trying to access

in config/app.js
```
const devEndpoint = isClient ? window.location.origin : 'http://localhost:3000';
const prodEndpoint = isClient && /^https:\/\/(www\.)?SITE_NAME\.com$/.test(window.location.origin) ? window.location.origin : 'https://SITE_NAME.com';

export const apiEndpoint = isDebug ? devEndpoint : prodEndpoint;
```

You dont have to use `www`. Its a subdomain that you can use when configuring your production domain

**Comment by rihannarickeminem** [comment]
@slavab89  seems like i've found some solutions, seems that its related to JSONP
its like this 
`class Tumblr {
  constructor(url = document.location.href) {
    this.url = encodeURIComponent(url);
  }
  getCounter() {
    let callback = ('cb_' + Math.random()).replace('.', '')
    let count_url = 'https://api.tumblr.com/v2/share/stats?url=' + this.url +
      '&callback=' + callback;
    window[callback] = function(counter) {
        console.log(counter.response.note_count)
        script.parentNode.removeChild(script)
    }
    let script = document.createElement('script')
    script.src = count_url
    document.body.appendChild(script)
  };
}

new Tumblr().getCounter();`

i am in searching how to make it much prettier with react now, maybe you have any suggestion how to do such calls with react in right manner? Or that i've found is wron? Sorry , if  i was not correct in question, but the REQUEST i expect to work, is not to my local server, but to any other servers like tumblr in example

**Comment by slavab89** [comment]
If you're trying to use tumblr then maybe their official module will help you [tumblr.js](https://github.com/tumblr/tumblr.js). I dont have experience with it though. You might also need a [api key](https://www.tumblr.com/docs/en/api/v2#auth)? 

Regarding JSONP (Which seems like the script that you've added is doing, kinda)..
Axios does not support JSONP requests. If you need such a request then you can use the [following solution](https://github.com/mzabriskie/axios/blob/master/COOKBOOK.md#jsonp)
JSONP does have its [drawbacks](https://security.stackexchange.com/questions/23438/security-risks-with-jsonp) and the server side - in your case tumblr - needs to support this. [Read more](https://www.sitepoint.com/jsonp-examples/)

Another solution for you (When using this boilerplate) is to send the request to the server side of the app and then make a request from the server side to the 3rd party API.

**Comment by rihannarickeminem** [comment]
@slavab89 ,  i want the tumblr data to be fetched directly from client side of application . I am using `https://www.tumblr.com/docs/en/api/v1`  it doesn't requires any `api keys`, its strange that there is no word `JSONP` on the documentation page

**Comment by slavab89** [comment]
We're trying to clean up the project and close issues.
This issue is not really related to this project but we can continue discussing it. Also, if you've found a solution, it would be great to have it here.
In case you still have an issue with this, please comment here or open a new issue.
