### ISSUE TITLE
Question: How to render fetched data?

### ISSUE THREAD

**Issue by stefvw93** [reactGo/reactGo#900]
### Description
- Type: Question

-----------------------------------------------------------------

## Question

**How to pass fetched data to state?**

I'm new to react-redux. After looking at the reactGo example code, I still have no clue whatsoever about how, for example, the topics data is rendered into the Vote page.

I was succesful in creating new database controllers and models, and fetching their data with the Router property ```fetchData={fetchMyData}```. But I don't understand how I will get the fetched data in my view?

Looking at app/containers/Vote.jsx, I see this: ```const {newTopic, topics, typing, createTopic, destroyTopic, incrementCount, decrementCount } = this.props;``` @ line 16.

WHERE DOES TOPICS VARIABLE COME FROM? I'm really really confused at this point and the readme or docs don't explain it very well.

Can somebody help me out please?

Edit: I guess I'm basically asking how to save fetched data into store

**Comment by ZeroCho** [comment]
```
function mapStateToProps(state) {
  return {
    topics: state.topic.topics,
    newTopic: state.topic.newTopic
  };
}
```

`react-redux` maps redux-state to react-props. Here, topics and newTopic of redux-state go to react-props.

**Comment by stefvw93** [comment]
Okay, but how do the topics get to redux state?

**Comment by stefvw93** [comment]
Server side

**Comment by slavab89** [comment]
You can read the Data Flow section in the Readme file, it explains the base idea and logic.
When you access the site, it reaches the server side naturally. Once there, an HTML should be returned to the client. This is what `middleware.js` file does. 
As part of the constructing of the HTML file (along with JS etc.) It performs [fetching of data](https://github.com/reactGo/reactGo/blob/master/server/render/middleware.js#L56). This causes redux store to update and create the initial state that the client should work with.

Once the html is returned to the client, `client.jsx` files is activated and starts to construct the whole react and redux structure. The [initial state](https://github.com/reactGo/reactGo/blob/master/app/client.jsx#L13) (That was constructed on the server) is put in redux store.
When the components render and activate the `mapStateToProps` functions, the data is already there and its populated to the component itself through `props`.

**Comment by stefvw93** [comment]
I get it now. I already understood what middleware.js did but I think client.jsx was my missing link. Thank you both!
