### ISSUE TITLE
Hot Reload is not working?

### ISSUE THREAD

**Issue by dlucidone** [reactGo/reactGo#901]
---------------------------------------------------------------
## Bug
**Expected Behavior** -  Hot Reload when changing any file

**Actual Behavior** -  It refresh sometimes and sometimes not.

**Steps to Reproduce** -  Tried adding a new page but failed to load content of it.

----------------------------------------------------------------

**Comment by slavab89** [comment]
Hot reloading does work. Please see if all your configuration is valid or if you've changed some things.
If you still have some problem, feel free to put some code example and we can try to help and point you in the right direction.

**Comment by dlucidone** [comment]
@slavab89 Thanks for the reply ! Reinstalling All modules fixed it.
