### ISSUE TITLE
Webpack 3

### ISSUE THREAD

**Issue by GGAlanSmithee** [reactGo/reactGo#902]
### Upgrade to Webpack 3

Webpack 3 [has been released](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b). Most interesting it introduces rollup style scope hoisting via the `webpack.optimize.ModuleConcatenationPlugin`. 

Scope hoisting means that the scope of each module will be hoisted to the top of the bundle, potentially greatly reducing size and parse time of the code.

Even if it's a major release, it shouldn't introduce any breaking changes, so I will make a PR when I get time, unless someone beats me too it.

**Comment by ZeroCho** [comment]
😢 `webpack.optimize.ModuleConcatenationPlugin` doesn't decrease the file size as much as I expected, but still I think it's good for ReactGo to apply that option.

**Comment by GGAlanSmithee** [comment]
@ZeroCho yeah true. From what I can see the size goes from **337.32KB** to **332.46KB** so that is certainly a modest amount. Reportedly, there is also the benefit of faster browser evaluation time. I haven't had time to test this though, and I think the application is really too small of a sample to get any conclusive eveidence. 

Having said that, I don't think there's any appearant drawbacks to upgrading!

**Comment by GGAlanSmithee** [comment]
#903
