### ISSUE TITLE
Css is applying slowly on components and change is visible?

### ISSUE THREAD

**Issue by dlucidone** [reactGo/reactGo#904]
## Question

**How to?**
I want to add other js and css files in this boilerplate right now I',m adding them in pageRenderer file but seems like my page css and jquery took a bit to refresh and css take time to apply.Dont know what is causing the delay.In the demo given i see no such delay.

**Comment by slavab89** [comment]
During dev, hot reloading is active therefore what happens is that styles are applied to components after they are loaded. This is the reason that you see like a "flicker" of the styling when you develop and add new styling and js.
If you try to run the production build (Like the Demi site is doing) then you should not see this happen

**Comment by dlucidone** [comment]
@slavab89 ok thanks a lot ! BTW can you suggest where should i put my external css and js files or cdn links in the project?

**Comment by slavab89** [comment]
I think you're correct in putting them in `pageRenderer`. You could also put them as part of the `assets` file - maybe even more "logical" cause the pageRenderer takes things from assets and builds the html there.

**Comment by dlucidone** [comment]
@slavab89 Thank you so Much !
