### ISSUE TITLE
node_modules library css fo `rc-time-picker`

### ISSUE THREAD

**Issue by rihannarickeminem** [reactGo/reactGo#906]
I am trying to include rc-time-picker css, how can i achieve this? How to enable any side library css ?

**Comment by ZeroCho** [comment]
just `require('/path/to/rc-time-picker.css')` on top.

**Comment by rihannarickeminem** [comment]
Dear @ZeroCho  where should i place  `if (isClient) {
  require('!style-loader!css-loader!prismjs/themes/prism-coy.css');
}` ?

**Comment by rihannarickeminem** [comment]
@ZeroCho I ve just got it  ! Just put on top of my jsx file
`const isBrowser = typeof window !== 'undefined';

if (isBrowser) {
  require('!style-loader!css-loader!rc-time-picker/assets/index.css');
}
`
Thank you!

**Comment by ZeroCho** [comment]
@rihannarickeminem 👍
