### ISSUE TITLE
Code Splitting?

### ISSUE THREAD

**Issue by ramakay** [reactGo/reactGo#908]
## Enhancement

** Initial app.js cost is high.

SSR is great but `app.js` is a big payload and [startrender](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/quick-start-quide#TOC-Start-Render:) is adversely impacted. 

Options:

1. React Router to dynamically load chunks , however SSR efforts were incomplete

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/code-splitting.md#code-splitting--server-rendering

Possible solution:

https://blog.emilecantin.com/web/react/javascript/2017/05/16/ssr-react-router-4-webpack-code-split.html 

2. Webpack dynamic imports

Does not seem to be straight forward. 

https://medium.com/webpack/how-to-use-webpacks-new-magic-comment-feature-with-react-universal-component-ssr-a38fd3e296a

Sadly, the synchronous nature of SSR - This whole things seems challenging, thoughts?

Apologies, if this was discussed earlier - please point me to the description

**Comment by slavab89** [comment]
There are a few PR's that try to achieve this
https://github.com/reactGo/reactGo/pull/841 (Does code split in RR3)
https://github.com/reactGo/reactGo/pull/880
But all seem to reach a dead end for now 😢 Its the combination or RR4, SSR, code split, hot reloading. Seems like its possible to achieve some of them but not all together.

If you have some additional insights or trials & experience that you've tried it would be great to know.

**Comment by ZeroCho** [comment]
Actually I succeeded in code splitting + server side rendering with RR4, but it has some breaking changes.
I think reactGo should adopt that in its next version.

**Comment by slavab89** [comment]
😱 Looking forward for this so much!! *\*Heavy Breathing\** 😆

**Comment by ramakay** [comment]
@slavab89 seems to be the way to go - split async and sync bundles and use webpack to replace at runtime. I am doing that with reactgo. 

https://blog.emilecantin.com/web/react/javascript/2017/05/16/ssr-react-router-4-webpack-code-split.html

@ZeroCho  - please share where you reached and if your approach was similar by using the `NormalModuleReplacementPlugin` 

Thanks guys, lets work towards this 👍

**Comment by ramakay** [comment]
Np, continue to play with the NormalModuleReplacementPlugin, it lead me to a necessary upgrade to Router 4 - what a drain :(

**Comment by slavab89** [comment]
Could one of you please share what you've achieved so far if possible?

**Comment by ZeroCho** [comment]
@slavab89 @ramakay Look #919
