### ISSUE TITLE
.env file to load config data

### ISSUE THREAD

**Issue by jcduran05** [reactGo/reactGo#912]
### Description
- Type: Enhancement

The databases.md outlines steps to change which db to use but it doesn't mention having to go to the db/[database_folder] to change user/password and database name. I'm also concerned about security with this method if it's a public repo.

Is there a way to make use of a .env file to load specific information like environment data at the moment or could this a potential enhancement that could be considered?

**Comment by ZeroCho** [comment]
It's up to you whether to use `dotenv` or not. Currently, heroku manages all `process.env` for reactGo demo app, so we don't need to use `dotenv`.
