### ISSUE TITLE
fetch single post from api

### ISSUE THREAD

**Issue by mulikaminker** [reactGo/reactGo#915]
i'm trying to build a blog with reactgo. in the home pgae (vote.jsx) i fetching list of post, and when the user click on a single post it's get the id from the routes.params and fetch single row from the db. 

the problem is - in both cases the data comes in state.post.posts array. it's the same object for a single or list of post, and when I switch from post to post I see the contents of the previous post for a second because it still exists in the store. 

routes.jsx: 

```
`const fetchOne = (Route) => {
  return postsService().getOne({id: Route.id})
  .then(res => res.data)
  .catch(() => []);
};
  return (
    <Route path="/" component={App}>
      <IndexRoute component={Vote} fetchData={fetchVoteData} />
      <Route path="login" component={LoginOrRegister} onEnter={redirectAuth} />
      <Route path="dashboard" component={Dashboard} onEnter={requireAuth} />
      <Route path="post/:id" component={Post} fetchData={fetchOne} />
    </Route>
  );
};`
```

**Comment by ZeroCho** [comment]
Well, you have to link that `postsService` to reducer so that newly fetched post can replace existing one.

**Comment by kamish24six** [comment]
@ZeroCho, Yes, but then when i go back to home page the post.posts list is empty...
i need to separate single post and post list in the store. 

I'd love to get an example

**Comment by trda** [comment]
Also you can create a new state for "onepost".

If you use topic.js as reducer, open it and add a new state like that:

`const onepost = (
  state = {},
  action
) => {
  switch (action.type) {
    case types.GET_ONE_POST_SUCCESS:
      return {
        id: action.id,
        title: action.title,
        detail: action.detail
      };
    default:
      return state;
  }
};`

And in your fetchOne function: dispatch the "type" 

`import { postsService } from '../services';
import * as types from '../types';

const fetchData = (params, store) => {
  return postsService(). getOne()
  .then(res => {
    store.dispatch({type: types.GET_ONE_POST_SUCCESS, data: res.data});
    return res.data;
  });
};

export default fetchData;`

To dispatch a type in fetchData function, please check this out: 
https://github.com/reactGo/reactGo/issues/527
