### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by davidychow87** [reactGo/reactGo#921]
I am trying to use async/await in the  backend routes, but I am getting an error: "regeneratorruntime is not defined"
I saw a similar issue: https://github.com/reactGo/reactGo/issues/866, but I don't quite understand how to get it to work,

I did the following:

npm install babel-plugin-transform-regenerator
npm install babel-plugin-transform-async-to-generator

In webpack/rules/javascript.js, i added 'transform-regenerator' and 'transform-async-to-generator' to the plugins array

I still get the error message - any help would be appreciated. Thanks in advance.

**Comment by GGAlanSmithee** [comment]
Babel uses regenerator for generators and async / await. You need to include a runtime before using this syntax. 

1. `npm i -D babel-regenerator-runtime` or `yarn add babel-regenerator-runtime`
2. in `Server/index.js`, at the very top, add `import 'babel-regenerator-runtime'`

There are other ways of doing it, like importing it with webpack, but this is the most straight forward way IMO

**Comment by ZeroCho** [comment]
@davidychow87 Or by using `babel-preset-env` instead of `babel-preset-es2015`. #889

**Comment by GGAlanSmithee** [comment]
Good advice @ZeroCho. Any specific reason the mentioned PR was closed?

**Comment by ZeroCho** [comment]
@GGAlanSmithee Due to confliction with react-route@4 PR. Doesn't mean that `babel-preset-env` has a confliction, but PR does.
