### ISSUE TITLE
Passport's req.isAuthenticated always returning false

### ISSUE THREAD

**Issue by trda** [reactGo/reactGo#922]
I have written the below function to control if user is authenticated or not before firing a service method such as `getpaymenthistory`.

```node
app.post('/api/getpaymenthistory', ensureAuthenticated, paymentsController.getPaymentHistory);


function ensureAuthenticated(req, res, next) {
  if (req.isAuthenticated())
    return next();
  else
  {
    console.warn('ensureAuthenticated: isAuthenticated: false');
    res.redirect('/login');  
  }
}
```

However, the problem is that almost each time, when I fire the method, req.isAuthenticated() turns **false** even if I am login.

**Comment by slavab89** [comment]
Where do you fire this method from? Is this a route that you've defined on the serve side routes?

Make sure that you have this defined after all `passport` and `session` middlewares.
Moreover, between the different checks that you do, do you perform a full server restart? If so, is the session persisted at some place?

**Comment by trda** [comment]
[server/init/routes.js](https://github.com/reactGo/reactGo/blob/master/server/init/routes.js)

```node
  if (usersController) {
    app.post('/sessions', usersController.login);
    app.post('/users', usersController.signUp);
    app.delete('/sessions', usersController.logout);
  } else {
    console.warn(unsupportedMessage('users routes'));
  }

if (paymentsController) {
    app.post('/api/createOrder', ensureAuthenticated, paymentsController.createOrder);
    app.post('/api/getpaymenthistory', ensureAuthenticated, paymentsController.getPaymentHistory);
  } else {
    console.warn(unsupportedMessage('paymentsController routes'));
  }

function ensureAuthenticated(req, res, next) {
  if (req.isAuthenticated())
    return next();
  else
  {
    console.warn('ensureAuthenticated: isAuthenticated: false');
    res.redirect('/login');  
  }
}
```

The above code is my server route.js source code. The check function is directly in this file. 

**Scenario**
1. User logins the system.
2. User sees the dashboard page.
3. User sees the payment history link in the dashboard page and clicks on it.
4. User sees successfully the list of payments in this page.
5. User clicks on the refresh button of the browser.
6. Client's [route file](https://github.com/reactGo/reactGo/blob/master/app/routes.jsx) calls fetch function.
```node
<Route path="paymenthistory" component={PaymentHistory} onEnter={requireAuth} fetchData={fetchPaymentHistory}/>
```
7. Fetch function calls the getPaymentHistory service.
```node
const fetchData = (params, store) => {
  return orderService().getPaymentHistory()
  .then(res => {
    if(res.status === 200) {
      store.dispatch({type: types.GET_PAYMENT_HISTORY_SUCCESS, data: res.data});
      return res.data;
    }else{
      store.dispatch({type: types.GET_PAYMENT_HISTORY_ERROR});
      return;
    }
  });
};
```

8. It fires the `/api/getpaymenthistory` method. 

```node
getPaymentHistory: () => client.request({
      method: 'POST',
      url: '/api/getpaymenthistory',
      data: {   
      }
    }),
```

9. The method first calls `ensureAuthenticated` function.
```node
app.post('/api/getpaymenthistory', ensureAuthenticated, paymentsController.getPaymentHistory);
```

10. The function returns false.
11. User is directed to login page in order to login again.

**Comment by slavab89** [comment]
Thanks a lot for the detailed explanation!!
First you can read about general info [here](https://github.com/reactGo/reactGo/issues/909)

Moreover, this happens to you during the initial SSR when the server side runs the `preFetch` logic.
Basically, the `axios` instance that's running on the server side does know know anything about the cookie that arrived with the request.

What you want to do is the following on the server side - you can put it on the [middleware.js](https://github.com/reactGo/reactGo/blob/master/server/render/middleware.js) before performing the `fetchDataForRoute `.
```js
if (req.cookies._session) {
  axios.defaults.headers.common.Cookie = `_session=${req.cookies._session}`;
}
```
where `_session` is the name of your session cookie. You can use `cookie-parser` package to parse the cookie header.

You should put a default configuration for `axios` on the server side and include the cookie of the current use.
The preferred way is to do that only on the specific instance of `axios` but the current code doesnt really allow that easily.

**Comment by trda** [comment]
What I understood is this is the way how "reactGO" works, it is not my bug. Saving session's authentication info after refreshing. Isn't it a basic requirement of all applications? I mean, Why didn't it come up with the initial version of reactGO.

**Comment by trda** [comment]
Another interesting thing is that after "ensureAuthenticated" returns "res.redirect('/login');", some text starts to show respectively at the bottom left corner of the interface.  

**Text:**
`
\n \n \n \n \n \n \n \n \n \n"},"routing":{"locationBeforeTransitions":null}}
`


![screen shot 2017-09-14 at 16 53 00](https://user-images.githubusercontent.com/4353845/30433415-1175c992-996d-11e7-95b3-19de93129dc0.png)

I have checked the place of text where they come from. 

![screen shot 2017-09-14 at 16 56 45](https://user-images.githubusercontent.com/4353845/30433728-e5cf5938-996d-11e7-8707-b322ab4f1bec.png)

It seems that it is coming from `${JSON.stringify(initialState)}` value.

![screen shot 2017-09-14 at 16 56 55](https://user-images.githubusercontent.com/4353845/30433731-ea2c5224-996d-11e7-906a-f21b89883116.png)

```node    
<script>window.__INITIAL_STATE__ = ${JSON.stringify(initialState)}</script>
```

I guess the method I used is not proper way for reactGo. I am not sure how can I control if user is login or not at the backend service([route.js](https://github.com/reactGo/reactGo/blob/master/server/init/routes.js)). 

I would appreciate if you could let me know how it is possible, what is the best-approach to check user's login state in the backend service?

**Comment by slavab89** [comment]
Sessions and user logins are saved properly, when you login and navigate through your site and do `fetch` requests you get all the data and your `ensureAuthenticated` works.

Once you click on the browser "refresh" button you force the browser to reload the page - Go to the server and fetch the initial HTML from scratch.
When you do that you initiate the SSR flow, which as part of it prefetches some data. To do that prefetch, the server needs to send a request to itself (using `axios` library). `axios` is not aware of the request or the context of the request - It doesnt know anything about the session cookie that came with the request.
What i've suggested earlier is how you can let `axios` know about this cookie so that when it will send a HTTP request, the request will contain that cookie header.

On another note, `req.isAuthenticated()` tries to find the session cookie and fetch the relevant use info from the session store.

@choonkending maybe we should add this logic of the session cookie to the boilerplate because it does seem like a common use case.

**Comment by trda** [comment]
slavab89, thanks for your help. Your description became so helpful. 
I preferred to use a different workaround for this issue instead of operating on `axios`.

When the server `route.js` sends 401 to the client, I catch it in the `middleware.js` with the below code, and redirect user to the main page. Main page doesn't require any authentication. Therefore user can continue to use web page after this first loading.

```node
        fetchDataForRoute(props, store)
        .then((data) => {
          store.dispatch({ type: types.REQUEST_SUCCESS, data });
          const html = pageRenderer(store, props);
          res.status(200).send(html);
        })
        .catch((err) => {
          if(err.response.status == 401){
            store.dispatch({ type: types.REQUEST_FAILURE });
            res.redirect('/');  
          }else{
            console.error(err);
            res.status(500).json(err);
          }  
      });
```
I think, in any case, there should be `if(err.response.status == 401){` this kind of a check in the catch function to dispatch `REQUEST_FAILURE`. Otherwise, the catch function always crashes the system with code 500. 

I hope, you or @choonkending implement a robust solution for this issue.

**Comment by slavab89** [comment]
We've just merged a commit that should fix the issue that you had.
Regarding the handling of a not authenticated user that you did might be a bit different for each one but i agree with the general suggesting that you offer - redirect him to `/`.
