### ISSUE TITLE
alternative to nodemon

### ISSUE THREAD

**Issue by GGAlanSmithee** [reactGo/reactGo#924]
## Description

It is  super frustrating to have `nodemon` do a full re-load, re-bundle and re-serve on every server change, taking a long time as well as detaching any attached chrome remote debugger. I suggest replacing `nodemon` with a minimal `chokidar` setup, providing a far better developer experience (dx) IMO.

### Enhancement

`nodemon` does not provide a good dx in the sense that on every change on the server it

1. re-runs `npm run dev`
2. compiles the entire frontend (which can take **minutes** on large code bases)
3. reloads browser

### Suggested enhancement
A better way to do it would be to do an incremental re-load of only the module/script that has changed. This is actually very easy to achive, using only native modules, and I've seen it used in `webpack`/`react` stack projects before.

#### Pros

1. no need to re-run any npm scripts
2. only changed code gets reloaded
3. no need to re-compile frontend bundle
4. no need to re-load browser and re-serve assets
5. server changes gets applied in under a second compared to 30 sec - minutes
6. if you are remote debugging using `node --inspect` your debugger stays attached

#### Cons

1. client browser is not automatically refreshed (this can be a pro if you only changed an API route etc, which does not require a browser refresh, and othervise you can manually refresh it)
2. there would have to be some minor refactoring of server entry point (I can do that if you would like to see this happen)

#### Example code

_disclosure: I am pretty sure this code is from another OS webpack/react boilerplate, but it was so long ago that I copied it, I cannot find the project ATM_

```javascript
const chokidar = require('chokidar')
    
// Do "hot-reloading" of express stuff on the server
// Throw away cached modules and re-require next time
// Ensure there's no important state in there!
const watcher = chokidar.watch(['./server', './app' ])

watcher.on('ready', function () {
    watcher.on('all', function () {
        console.log('Clearing /server/ and /app/ module caches from server')

        Object.keys(require.cache).forEach(function (id) {
            if (/[\/\\](server|app)[\/\\]/.test(id)) delete require.cache[id]
        })
    })
})

// Do "hot-reloading" of react stuff on the server
// Throw away the cached client modules and let them be re-required next time
compiler.plugin('done', function () {
    console.log('Clearing /client/ and /src/ module caches from server')

    Object.keys(require.cache).forEach(function (id) {
        if (/[\/\\](client|src)[\/\\]/.test(id)) delete require.cache[id]
    })
})
```

ping @choonkending @ZeroCho

**Comment by GGAlanSmithee** [comment]
Here is some related information:

* https://medium.com/@kevinsimper/dont-use-nodemon-there-are-better-ways-fc016b50b45e
* https://gist.github.com/kjs3/936a1a4a90dc36f407a2

**Comment by slavab89** [comment]
If you dont have server-side render in development mode it can be an issue sometimes no? Meaning that you wont really be able to test that it works correctly?
To make it work you would have to trigger a webpack/babel rebuild on the server side as well? (not full rebuild but only HMR on the server).

BTW, what i suggested on the other issue regarding not running babel on the whole server code (and only on the react stuff) would probably allow to use this setup with `chokidar`. But, like you've stated, it will require "two codebases" since the server is pure Node.js and the react stuff is ES17 or whatever

**Comment by GGAlanSmithee** [comment]
@slavba89 I agree with all your statements, and have come to the same conclusions myself.

I still think that removing `nodemon` would be great, but it will require a bit more work. As you said, the way to go is to use webpack/babel on the server, with incremental rebuilds, just like on the client.
