### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by GGAlanSmithee** [reactGo/reactGo#925]
[React 16 has been released.](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html)

This brings a lot of new really cool features. Let's discuss how(if) we can make use of things such as `fragments`, improved server-side rendering, error boundries etc.

**Comment by againksy** [comment]
And webpack 3 please! , What about react-router 4, does it work for server side rendering?

**Comment by GGAlanSmithee** [comment]
@againksy see https://github.com/reactGo/reactGo/pull/919

**Comment by againksy** [comment]
@GGAlanSmithee But why we dont have react-router-4 master?

**Comment by GGAlanSmithee** [comment]
@againksy I don't know, you'd have to ask the maintainers. There is an open PR (the one I linked) and another WIP by @choonkending, but I don't know the status of them.
