### ISSUE TITLE
dispatch is not a function

### ISSUE THREAD

**Issue by HarishKalepu** [reactGo/reactGo#930]
Note: i create one action & reducer like users [contests] but i am getting dispatch is not a function 

please find the attched screen shot

https://fankickdev.blob.core.windows.net/images/Untitled.png 

### Description
- Type: Bug | Enhancement | Question
- Related Issue: `#abc`

---------------------------------------------------------------
## Bug
**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

----------------------------------------------------------------
## Enhancement

**Reason to enhance/problem with existing solution**

**Suggested enhancement**

**Pros**

**Cons**

-----------------------------------------------------------------

## Question

**How to?**

**Comment by HarishKalepu** [comment]
import { push } from 'react-router-redux';
import { contestService } from '../services';

import * as types from '../types';

function beginContest() {
    console.log("IN beginContest");
    return { type: types.CONTEST1_REQUEST };
}

function contestSuccess(data) {
    return {
        type: types.CONTEST_REQUEST_SUCCESS,
        contests: data.data
    };
}

function contestError(message) {
    return {
        type: types.CONTEST_REQUEST_ERROR,
        message
    };
}

export function getContest() {
    console.log("IN getContest");
    return (dispatch) => {
        console.log("IN getContest dispatch");
        dispatch(beginContest());

        return contestService().getContests()
            .then((response) => {
                dispatch(contestSuccess(response.data));
                dispatch(push('/'));
            })
            .catch((err) => {
                dispatch(contestError('Oops! Invalid username or password'));
            });
    };
}

**Comment by slavab89** [comment]
How do you use the `getContest` function? Where do you call it? 
Did you wrap it with Redux `connect` or `bindActionCreators`?

**Comment by GGAlanSmithee** [comment]
@HarishKalepu are you still having problems with this? Could you please answer @slavab89s question?

**Comment by slavab89** [comment]
I'll close this since it is probably a misunderstanding with the code usage rather than an actual issue with the project. Lets continue to talk here though if there is still an issue
