### ISSUE TITLE
Save data to DB

### ISSUE THREAD

**Issue by markolofsen** [reactGo/reactGo#934]
## Question
I do not understand, how to dispatch some data to reducer and after save to DB (Mongo)?

**Comment by GGAlanSmithee** [comment]
@markolofsen 

Saving to the db takes place on the server, dispatching actions takes place on the client. The only time we use redux on the server is on the initial rendering. 

A simple flow would be to:
1. trigger a redux action on the client (SAVE_DATA)
2. send an AJAX request with the data to the server.
3. On the server, persist the data to the DB
4. Return a status code
5. On the client, when the AJAX request responds
5a. If the reponse is succesfull, fire another redux action (SAVE_DATA_SUCCESSFUL)
5b. If the reponse is failed, fire another redux action (SAVE_DATA_FAILED)
6. On the client, in your reducer, handle each action.
6a. For example, if succesful, add the data to the redux store

There are a lot of optimizations you can do, like optimistic updates etc, but this should get you started. If you look at the [Redux docs](https://redux.js.org/docs/introduction/) there is a ton of examples which you can read up on.
