### ISSUE TITLE
As now module `import`and `export` enabled in node.js 9, we can remove babel for server side?

### ISSUE THREAD

**Issue by IzaGz** [reactGo/reactGo#935]
As now module `import`and `export` enabled in node.js 9, we can remove babel for server side?

**Comment by GGAlanSmithee** [comment]
@IzaGz that won't ever be possible because we are using react on the server side. Also, we cannot count on everyone using the latest version of node. Thanks for the suggestion though.

**Comment by GGAlanSmithee** [comment]
As a side note, we should probably use `babel-preset-env` instead of `babel-preset-es-2015`, which will give the user a bit more control.
