### ISSUE TITLE
When will you implement the Token Based Authentication?

### ISSUE THREAD

**Issue by sunkant** [reactGo/reactGo#94]
This project is very good, but when will you implement the Token Based Authentication? : )

**Comment by choonkending** [comment]
@Luke currently looking to tidying up and using Redux better and then
writing tests. When would you like this out?

If you have a solution for this already, happy to help out or check a PR :)

**Comment by lukeqi** [comment]
Hi @choonkending Actually I am looking for a way to use Token based auth with Redux, but I encounter some problem and I am still working on it.

This project: https://github.com/nicolashery/example-isomorphic-one
Uses SSR, Token based Auth with Fluxible front framework, and I think this project shows a possible way to solve it.

**Comment by lukeqi** [comment]
It load token from request cookie first every time when a page refresh request arrive on the server.

However, when I look at this project (which is very hot on github):
https://github.com/erikras/react-redux-universal-hot-example

It uses session based auth (as your project), and loads api from another server when doing SSR. This adds complexity when trying to do SSR if using token based auth.

**Comment by lukeqi** [comment]
Like if we want to load api from another server (or different port in the same host, like localhost):

The "another" server need to obtain the Token from the cookie of the api Post,

So, when our SSR server issues the api Post, it must have something like a HTTP Interceptor, which adds the Token from the original request from the user.

Angular has such a thing like "HTTP Interceptor", but I do not find a similar one in Reactjs.

**Comment by choonkending** [comment]
@lukeqi Sorry I took a while to get back on this. Yes, this looks interesting. I'll have to read up on token based authentication, but I think it's a good approach to the one we're currently having. :)

**Comment by choonkending** [comment]
I think this has been sitting on the back burner for a while now. It should be the next thing we look at after abstracting DB. 

**Potential references**
1. [https://davidwalsh.name/react-authentication](https://davidwalsh.name/react-authentication)
2. [https://jwt.io/](https://jwt.io/)

**Comment by mjewell** [comment]
Is anyone currently working on this? I'm happy to take a look at it

**Comment by choonkending** [comment]
Go ahead! I don't think anyone is :)
