### ISSUE TITLE
Chrome devtools css strange classes

### ISSUE THREAD

**Issue by IzaGz** [reactGo/reactGo#949]
How can i turn the css class names in devtools to be shown ass real class names that i have in the source code- instead of strange characters set ? It is very annoying - then i look in code in browser- i dont know which real class name the element has in the source code in editor=(

**Comment by ZeroCho** [comment]
It's not the strange thing but it's a hash string.
We don't use real class names because they can collide.
You can find where hash string comes [here](https://github.com/reactGo/reactGo/blob/master/webpack/rules/css.js)

**Comment by againksy** [comment]
i have changed it - but nothing changed- still strange class names- its very annoying, when i am trying to find the required div by classname- but i cant - cause its name is strange hash

**Comment by GGAlanSmithee** [comment]
@againksy what did you change it to? Please paste it here, or link to your config, if public.
