### ISSUE TITLE
Including stylesheets from UI frameworks (Material UI, UIkit, antd etc.)

### ISSUE THREAD

**Issue by m-liddell** [reactGo/reactGo#952]
I've tried a few different UI frameworks (Material UI, UIkit, antd etc.) to have some easy components to use. Though the components work, each one seems to fail on inclusion of their stylesheets:

_Module parse failed: /node_modules/antd/lib/input/style/index.css Unexpected token (5:0)
You may need an appropriate loader to handle this file type._

I'm guessing it is an issue with Webpack and the server-side rendering?

Has anyone used additional stylesheets successfully?

**Comment by Shelyo** [comment]
You might have a look into the following issue:
https://github.com/reactGo/reactGo/issues/929

I managed to use antd with react-go, but unfortunately the solution is not optimal (I had to deactivate the css-modules). Another user there managed to use antd without doing so though.

**Comment by GGAlanSmithee** [comment]
@m-liddell there has been a few issues regarding inclusion of external styles. If I get some time over, I will have a look at it.
