### ISSUE TITLE
Postgres DB on port other than 5432

### ISSUE THREAD

**Issue by m-liddell** [reactGo/reactGo#956]
I'm not able to connect using a production build on to a postgres DB on port 543**3**

`Unable to connect to the sequelize database:  { SequelizeConnectionError: getaddrinfo EAI_AGAIN localhost:5433:5432`

My verified working connection string for a connection with node.js via PG is

`var conString = "postgres://myuser:mypassword@localhost:5433/postgres";`

I've tried putting it in like

```
username: 'myuser',
password: 'mypassword',
database: 'postgres',
host: '127.0.0.1:5433',
dialect: 'postgres'
```

and

```
use_env_variable: 'postgres://myuser:mypassword@localhost:5433/postgres',
dialect: 'postgres'
```

But it refuses to be used correctly and gives the above error with port 5432 appended.

**Comment by m-liddell** [comment]
I ended up hard coding it in /server/sequelize/constants.js and /server/sequelize/constants.js as a workaround.

Sequelize allows you to set the port building the connection string

`const sequelize = new Sequelize('database', 'username', 'password', {`
	  dialect: 'postgres',
	  host: "localhost",
	  port: 5433,
	});`

This probably need to be added in so all the connections to build, test and production can be held in the sequelize_config.js and be switched between as was seems to be intended.

**Comment by GGAlanSmithee** [comment]
Nice find @m-liddell.
