### ISSUE TITLE
Consider using easy-peasy on top of Redux

### ISSUE THREAD

**Issue by GGAlanSmithee** [reactGo/reactGo#967]
Redux is great!

But.. it's **very** verbose IMO, and tends to lead to a lot of boilerplating with actions, actionCreators, reducers, HoC's for connecting state etc.

[easy-peasy](https://github.com/ctrlplusb/easy-peasy) is an abstraction over redux which provdes a more consise API for setting up actions, uses hooks instead of connect while maintaining the great aspects of Redux such as performant global state, stateful hot reloading (I think), redux dev tools etc.

Let's check it out

**Comment by ZeroCho** [comment]
Hi, I'm back. I recommend [redux toolkit](https://redux-toolkit.js.org/)
