### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [reactGo/reactGo#969]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by GGAlanSmithee** [comment]
There is no CI.

Also, even though I appreciate you wanting to gather data for your research, both sending a mail and opening an issue is a bit of a overkill. this is an issuetracker, not a questionare.

**Comment by gustavosizilio** [comment]
Thank you very much. Im really sorry about that, but i did not received any response by e-mail. I appreciate your patience.
