### ISSUE TITLE
Signup error

### ISSUE THREAD

**Issue by kul1010** [reactGo/reactGo#970]
when sign up showing this error.

Access to XMLHttpRequest at 'http://localhost:3000/users' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

action SIGNUP_ERROR_USER @ 15:23:32.643
redux-logger.js:1  prev state {isFetching: false, topic: {…}, user: {…}, message: {…}, routing: {…}}
redux-logger.js:1  action     {type: "SIGNUP_ERROR_USER", message: "Oops! Something went wrong when signing up"}
redux-logger.js:1  next state {isFetching: false, topic: {…}, user: {…}, message: {…}, routing: {…}}

**Comment by GGAlanSmithee** [comment]
@kul1010 I'm guessing, since you closed the issue, that you got it working?

**Comment by kul1010** [comment]
Yes. I have include 
import cors from 'cors'; // for above error resolved after including cors module

const app = express();

app.use(cors());
